### ISSUE TITLE
Music is messed up

### ISSUE THREAD

**Issue by JulioBBL** [Frederikam/FredBoat#10]
The auto setting of the voice activation volume from discord messes up the music

**Comment by Frederikam** [comment]
Bots aren't affected by voice activation. It might be that you are experiencing packet loss, causing it to sound like the bot is stuttering. Usually, you can fix this by changing voice region.

**Comment by Frederikam** [comment]
Closing this as it's likely due to issues with Discord's voice servers or your connection.
