### ISSUE TITLE
Say “You are not in a voice channel” earlier

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#104]
"Just a little something that annoys me that would be great to fix. If a player is not in a voice channel, and they do ;;play [search], after they choose THEN it says “You are not in a voice channel”. Why not say that before doing the YT search? It saves time, and reduces the YT search count."

Picked this feature request up from the #suggestions channel

**Comment by Nanabell** [comment]
that should be an easy fix

**Comment by Nanabell** [comment]
This can be closed once we megre it back into master. see #111 
maybe stick a label on it to remember
