### ISSUE TITLE
;;report command

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#105]
Report command to report problems, internally attaching shard number to that report.

Picked this feature request up from the #suggestions channel

**Comment by kitkatdesu** [comment]
How would you implement this? Could it automatically report when 'an error occurred' is displayed (of course not for user-caused issues)?

**Comment by Frederikam** [comment]
No need to report exceptions automatically. Those are already being logged. It is also difficult to determine whose fault it is.

I'm thinking storing reports in a Discord channel would be best.

**Comment by napstr** [comment]
Closing this since we decided not to post exceptions to a channel for risk of flood when Discord or the bot has hiccups and I can't think of anything automated and unabusable that would be better than talking to people directly in out support channel when they are having problems.
