### ISSUE TITLE
MusicBot ... Delete a song in playlist

### ISSUE THREAD

**Issue by Undreamed** [Frederikam/FredBoat#11]
if there a command to remove songs from the playlist?

**Comment by Frederikam** [comment]
Currently, there's no way to remove a single song from a specific index, but you can use ;;skip to skip a song and ;;stop to completely clear the queue. I added this as an idea on my trello board:
https://trello.com/c/XnpfQK9w/18-command-to-remove-tracks-from-a-given-index

**Comment by Frederikam** [comment]
You can now skip a particular song given the index:
![image](https://cloud.githubusercontent.com/assets/2582617/21073320/15b8c83c-bedb-11e6-8096-c7e3a138dee4.png)

**Comment by ashlawless** [comment]
How do I remove a single song from the bots playlist? Also is there anyway for me to make ;;skip a moderator only command? To help stop people from trying to think there funny and adding stupid songs
