### ISSUE TITLE
Announce the currently playing track

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#110]
"Everytime a new song starts Fred should say so. with time and so If a new song starts"

This feels like it has been implemented (I thought I saw a code for it), but it's definitely not there, at least not in the way I'd expect it.

Picked this feature request up from the #suggestions channel

**Comment by Frederikam** [comment]
This is already a thing, but due to performance issues it is not available on the public music bot yet. Also requires the JDBC URL to be configured.

To enabled do:
`;;config track_announce true`
