### ISSUE TITLE
catgirl command is broken

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#112]
![image](https://cloud.githubusercontent.com/assets/6048348/24114008/ff6e2a14-0d9e-11e7-85d5-4bd2cf29bc87.png)

May be related to the source website using cloudflare.

**Comment by Frederikam** [comment]
Yes, I'm not aware of a fix yet.

**Comment by RealKC** [comment]
I supose we could look for a new catgirl site we could use for `;;catgirl`?

**Comment by Frederikam** [comment]
Sure
