### ISSUE TITLE
;;fulllist which has the music bot send you the full playlist in pm

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#125]
So you can see what like say: the 100th song would be in the playlist, when someone added 270 songs

picked up in #suggestions

**Comment by shikhir-arora** [comment]
+1 to this. (also - @napstr - your Spotify push works extremely well 👍 )

I would say that this is the only thing missing from the standpoint of larger queue management.

Could use pagination - or something simpler, even, like `;;list [num]` or `;;queue [num]` where num is a page, so if there are 200 songs loaded, `;;list 5` would take you to that page to see. The *only* complimentary command with that which would help "complete" that functionality would be a command that allows one to move a song from a position to the other, like `;;movesong 121 > 3` would move the song from position 121 to 3.

**Comment by napstr** [comment]
With the pagination of the `;;list` command (41d31a4680d9b46867df6b123efed78d4dd91edc) the use case for this should be served.
