### ISSUE TITLE
More short aliases for commands

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#126]
like ;;play = ;;p, ;;list = ;;l, etc

picked up in #suggestions

**Comment by Frederikam** [comment]
This would be a low hanging apple

**Comment by knight-ryu12** [comment]
Why not close this issue?

**Comment by napstr** [comment]
I don't see any of the examples in the first post implemented.

**Comment by knight-ryu12** [comment]
huh.
I thought that merged PR kills this issue :thinking:

**Comment by RealKC** [comment]
I mean, the two exact ones in the OP are kinda vague.

**Comment by napstr** [comment]
I disagree. They are easily the most iconic and often used commands, together with skip (which should get ;;s imo instead of shrug that has it assigned currently).

**Comment by Macley-Kun** [comment]
I agree to napstr. FredBoats core feature is about music. I rather would want even shorter commands to listen to music, rather then a silly shrug emoji that all the bots have, and even Discord itself!
