### ISSUE TITLE
Additional prefix for non-patron bots

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#129]
We need an additional prefix that the non-patron bots can respond to, so that patrons can use both bots in the same text channel.

Maybe use `::` as prefix?

**Comment by Nanabell** [comment]
why cant we change the prefix of the patron bot ?

**Comment by Frederikam** [comment]
Because patrons are already accustomed to `;;`. Maybe I can do a poll on Patreon

**Comment by Nanabell** [comment]
hmm even if i would say change the prefix on the smaller scale. Would only cause confusion if suddenly a second prefix would work for the main bot. If we decide to do a second prefix i would suggest adding it to Patron

**Comment by napstr** [comment]
#69 (customizable prefix) should solve this issue too.

**Comment by napstr** [comment]
Funny how this issue is actually fully solved (emphasis on the _non-patron_ part).
