### ISSUE TITLE
Patreon specific FAQ

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#130]
I need a new FAQ with patron-specific topics:

1. How to get the bot
2. What the benefits are
3. How to use both bots at the same time (#129)

**Comment by RealKC** [comment]
Aren't 1 and 2 done with the existance of the [donate page](https://docs.fredboat.com/donate)?

**Comment by Frederikam** [comment]
Yes

**Comment by RealKC** [comment]
To use the public bot in the same server as the patron bot, you need to make one of the bots unable to send and read messages in the channel you want to use the other one right?

**Comment by Frederikam** [comment]
Yes, the patron bot should be unable

**Comment by RealKC** [comment]
This would go in the FAQ section of the docs, right?
