### ISSUE TITLE
Discord.FM support

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#131]
https://temp.discord.fm/

Not a "real" radio, they basically have a few genre oriented playlists which I think would be nice to support for us, either as a paste service provider from the musicbot links (https://temp.discord.fm/libraries/[listname]/musicbot), or in a more sophisticated way where turning them on is like turning on a radio stream with us loading the tracklists and continually playing tracks from them for those guilds that tune in.

**Comment by napstr** [comment]
This could be related to #95

**Comment by Frederikam** [comment]
Could work. If lots of people use it we could save some resources by making it a stream, though that makes things much more complicated than loading a playlist. I'm actually going to add two difficulty tags.

**Comment by deansheather** [comment]
Regarding the Discord.FM web server thing at temp.discord.fm, you'll find that the data is a lot more consistent when using the JSON endpoints (`https://temp.discord.fm/libraries/library-name/json`) and reading information only from `service` and `identifier` fields. If you need to use the `url` fields or the `/musicbot` page, please verify all URLs before playing them with a YouTube or SoundCloud regex. We don't use the `url` field internally (so we aren't motivated to fix inconsistencies) and we've had a few bugs with storing the wrong values in the wrong keys in the database (curse schema-less databases) and you might find some funky data such as user IDs as the `url` field. If you'd like me to fix the database, I can probably do it tomorrow.

Regarding radio streams, we supply a queue endpoint and a wss server (`/libraries/queue`, `wss://sockets.discord.fm`) but we do not recommend using these for your radio streams as any crashes/skips in the main Discord.FM server may desync your radio stream or cause skips for all users listening through your bot.

Additionally, if you implement a Discord.FM feature or add Discord.FM support to an existing feature please acknowledge us somewhere with a link (doesn't have to embed, and you can chuck us in the `help` command for whatever command you implement this to) to https://discord.fm.

I'm a developer for/the owner of Discord.FM.

**Comment by Frederikam** [comment]
Closing this issue because of what happened to Discord FM and how it got rebranded.
