### ISSUE TITLE
Revive a Shard based on GuildId

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#138]
I know we are implementing a watchdog #137 but it might also be useful to have a admin command that can revive a shard based on guild id. We might not catch all problems with the Watchdog and it would be easier to revive a shard based on the guild Id than waiting for Fred to come and use a Eval to find out the Shard number

**Comment by napstr** [comment]
01b370ee1f5f19f9efbca4cec5fdf05e8d8b39cb implements this.
