### ISSUE TITLE
Pages for ;;list

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#145]
There was some discussion about pages for list in #34, so I'll post a screenshot of what was discussed there:
![quote](https://fred.moe/GTa.png)

Also -Zero#0856 has suggested this in #suggestions, this is what he said:
>;;list
shows first X tracks
;;next
shows next page of X tracks
;;next/;;prev, maybe ;;p<page number>
displays requested page

In this case I think Fredboat should delete the old `;;list` message and make a new one, page number should be indicated somewhere very visible.

I was also thinking of using reactions(`:arrow_left:` and `:arrow_right:`) to switch between pages, in this case I think editing the `;;list` message would be a better idea, this should be indicated in the `;;list` message.

**Comment by Frederikam** [comment]
Would it not be simpler to just do ;;list 2, ;;list 3 etc?

**Comment by RealKC** [comment]
You're right, `;;list 2` would be simpler than `;;page 2` or `;;p 2`

**Comment by Frederikam** [comment]
Now working on this

**Comment by Nanabell** [comment]
this can be moved to done in the roadmap as of 41d31a4680d9b46867df6b123efed78d4dd91edc :^)

**Comment by Frederikam** [comment]
It hasn't been deployed yet

**Comment by Nanabell** [comment]
neither is destroy and its in the done tab. 🤔. Did i interpret to much ?

**Comment by Frederikam** [comment]
Oops

**Comment by Frederikam** [comment]
I thought you meant I should move it to deployed

**Comment by RealKC** [comment]
Closing this as the feature has been deployed for 4 days(and done for at least 23 days).

**Comment by Frederikam** [comment]
It has been deployed for weeks 👀

**Comment by RealKC** [comment]
You only moved it to deployed 4 days ago tho
