### ISSUE TITLE
Test fail: Could not create JDA object for tests

### ISSUE THREAD

**Issue by InterXellar** [Frederikam/FredBoat#157]
I'm having Issuses to compile the Bot i tried on Linux and on Windows following your Guide i already compiled your Bot once successfully but with the newest Commit it wont Compile.

This is the Error. (If needed i can try to compile with -X and send you a full Log)
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project FredBoat: There are test failures.

**Comment by napstr** [comment]
Which tests are failing and with what errors?

If you don't care for tests you can run it with -DskipTests.

**Comment by InterXellar** [comment]
default-test are failing, i will try that. My Server can't compile the Bot too.

**Comment by Frederikam** [comment]
If you're not providing the log, we're essentially blind here.

**Comment by napstr** [comment]
I do not know of a thing called "default-test" in FredBoat.

There are tests, and all of them are run by default. Again: Which tests are failing, and with what errors? You have to look into the log you are getting from maven to answer these questions.

**Comment by InterXellar** [comment]
https://pastebin.com/J7PrU7n8 here but if i skip the tests it will compile

**Comment by napstr** [comment]
Hi, that exception is known to me, it will be removed in the near future.

But it does not cause the tests to fail for me.

Please post the full log where it exactly says which tests failed.

**Comment by napstr** [comment]
Nvm that, I think I reproduced it.
Log still highly welcome.

**Comment by InterXellar** [comment]
I do -X to do a Debug Log but i wont save the Log is there another command to generete a Log?

**Comment by InterXellar** [comment]
Never mind got it here: https://pastebin.com/30DtLSbk

**Comment by Frederikam** [comment]
You should now be able to compile the bot if you clone this repo again.
