### ISSUE TITLE
Akinator breaks after question 80

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#164]
After question 80 Akinator breaks with this [error](https://hastebin.com/fuwajihije.erl), which makes sense since after question 80, the website puts you to pick from a two option list to continue the game(if you cannot find your character, you give a name, then pick from another list, then Akinator congratulates you).

Possible fixes:
1. Make Fredboat congratulate the user if they win.
2. Make Fredboat make the user go through the process that the site makes you go through after question 80.

**Comment by Frederikam** [comment]
Nah, let's just finish the game at that point in a graceful manner

**Comment by napstr** [comment]
Guess github auto closes this only when the commit ends up in the master branch?

**Comment by Shredder121** [comment]
> Guess github auto closes this only when the commit ends up in the master branch?

That's correct, or at least the 'default' branch.
