### ISSUE TITLE
Admin announcement when restarting. 

### ISSUE THREAD

**Issue by OrigSilverwolf** [Frederikam/FredBoat#174]
As per mentioned, It would be good to have a announcements push to all active players if a team member uses sigterm or mbotrestart. 
<img width="657" alt="screen shot 2017-05-08 at 11 22 41 pm" src="https://cloud.githubusercontent.com/assets/26029079/25834386/a05cb75c-3445-11e7-969b-cff620821515.png">

**Comment by Frederikam** [comment]
For restarting? Why not in general?

**Comment by OrigSilverwolf** [comment]
it would be nice to have both. Admins should be able to do some announcements on the fredboat server, but would also be nice that when the bot is restarting, the admins can push a message to the servers that have players active, saying "I'm about to restart, your music will be saved, give me a second to start up and your music will continue."
this was people dont have to ask if the bot is restarting, they know it is restarting and just doesnt quit all of a suddon.

**Comment by napstr** [comment]
Actually there is an automated announcement for playing players doing exactly that already.

**Comment by Frederikam** [comment]
@napstr I'm not sure how well that works. The shutdown hook doesn't seem to be able to finish. Maybe it is the JVM enforcing a short timeout?

**Comment by napstr** [comment]
What we want is an announcement kind of command I think, with scopes all / music playing / etc.

I don't know of any limitations to the shutdown hook by the JVM. Even a SIGTERM should let it run until it's done, only a SIGKILL or crash of the JVM should really interfere with the shutdown hook.

**Comment by Frederikam** [comment]
"All" I hear you say?
![gif](http://i.imgur.com/P6bDtR9.gif)

**Comment by Frederikam** [comment]
I forgot to mention it here, but there is now an ;;announce command that broadcasts a message to all active text channels playing music
