### ISSUE TITLE
Why the bot is offline

### ISSUE THREAD

**Issue by Vizancio98** [Frederikam/FredBoat#176]
![image](https://cloud.githubusercontent.com/assets/28635216/25971199/4f45daa6-3693-11e7-8570-2487b700a1ea.png)
How can I put it online again, i cant use ;;commands or ;;play a music.
Please help :c

**Comment by Nanabell** [comment]
This can be closed. Please join our Discord Server and check for any updates on the bots status before opening an issue. We're way faster to respond there.

**Comment by Frederikam** [comment]
For the record, this was caused by an issue with our host automatically nullrouting our bot for suspected DDoS.
