### ISSUE TITLE
.aac file compatibility

### ISSUE THREAD

**Issue by ibigfire** [Frederikam/FredBoat#178]
The ability to play .aac files like http://ckpk.streamon.fm:8000/CKPK-192k.aac would be nice.  Not a big deal, but it would be a nice bonus if you ever feel like including it.

**Comment by Frederikam** [comment]
You might want to submit that idea to https://github.com/sedmelluq/lavaplayer/issues

We play all our audio through Lavaplayer.

**Comment by ibigfire** [comment]
Huh.  Interesting.  They say they do support AAC!  But I'll move the issue over there to see if they can sort out why that particular URL isn't working.  Thanks very much for pointing me in the right direction.

**Comment by ibigfire** [comment]
Apparently this is fixed as of lavaplayer 1.2.50 [https://github.com/sedmelluq/lavaplayer/issues/37#issuecomment-365778445](url) but for some reason I still cannot get it to play.  Hm...

**Comment by napstr** [comment]
Works for me. On which version did you try this?

**Comment by ibigfire** [comment]
The patreon Fredbot.  Not sure how to check version of that.

**Comment by shikhir-arora** [comment]
Use the `{prefix}stats` command. But the bot should be at 1.2.50 +

**Comment by ibigfire** [comment]
Ah, well there we go.  The Patreon bot is not, that's why.  It is at.

JDA version:                    3.5.0_332
FredBoat version:               2.2_1618
Lavaplayer version:             1.2.47

**Comment by shikhir-arora** [comment]
👀 The main bot is at 1.2.51 so I assumed it would. I'm sure @napstr or @Frederikam  will take care of that in a few though. I've been a patron for a while but I self-host so never used the patron bot, assumed it would be updated though.

**Comment by napstr** [comment]
Yeah we aim for stability with the patron bot - so it usually laggs up to one update behind the public bot. Should get the new code soon though.

**Comment by napstr** [comment]
Should be updated now.

**Comment by ibigfire** [comment]
That makes total sense.  And yep!  All working now, yay!  Thanks so much!
