### ISSUE TITLE
Check for other music bots playing already

### ISSUE THREAD

**Issue by aliasfalse** [Frederikam/FredBoat#181]
**Requested:** Check if a speaking user in the voice chat a user is in is a bot. If so, warn the user or don't join the voice chat
Configurable:
* Ignore that there's another bot speaking and join anyway
* Warn
* Don't join

**What I mean:** Before joining a voice chat to play music, check if there is a bot and if it is speaking. Marking this with a warning or not joining would help prevent accidental instances of multiple music bots playing in one channel.

**Comment by Frederikam** [comment]
There's no way to know if someone is speaking without joining the same voice channel. I don't see an elegant way of doing this. Most people just create separate channels to prevent this from happening.

**Comment by knight-ryu12** [comment]
I honestly don't recommend this thing, because of how ;;join works.
As Fred said.

**Comment by aliasfalse** [comment]
Looks like there's a "getVoiceState" on the "guildMember" object
http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/entities/Member.html

**Comment by aliasfalse** [comment]
What about how `;;join` works would prevent this from working?

**Comment by knight-ryu12** [comment]
Currently ;;join is doing `Just join`.
if you want include em, we need to change command too.

**Comment by Frederikam** [comment]
GuildVoiceState does not expose a method to tell if a user is speaking.

**Comment by aliasfalse** [comment]
I'll be more generic, then, just telling if it's in a voice channel would be enough, and just saying "there's another bot in there, just so you know"

**Comment by Frederikam** [comment]
To be honest, I don't really see the use of this. If a user is trying to troll the voice channel, moderation can step in, or mods can create separate channels.

**Comment by knight-ryu12** [comment]
Also we can move CurrentPlayer with Discord default thing

**Comment by aliasfalse** [comment]
except when mods can't separate channels cause perms and admins are inactive in a massive server XD
it's more that the mods can't do anything about it, and admins are unwilling to lock them to channels,
so users end up accidentally using the wrong prefix and bringing another bot in and having them both play at once.

yes, i realize it's more of a moderation problem then yours, but it'd be helpful, is all i mean.

**Comment by napstr** [comment]
Just use ;;leave to get rid of FredBoat in your channel if you invited it accidently.

**Comment by aliasfalse** [comment]
right, but we'd also rather not have random people popping in and `;;leave`-ing the bot when others are listening to music

**Comment by Frederikam** [comment]
This issue has nothing to do with the ;;leave command

**Comment by aliasfalse** [comment]
i know, i didn't bring it up
