### ISSUE TITLE
Debug Information for Fredboat Admins

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#183]
In Detail its a Fredoat Admin restricted command to get some debug information about the current server + associated player is existent to figure out what might be wrong

**Comment by Nanabell** [comment]
ffs pressed enter, 
In Detail its a Fredoat Admin restricted command to get some debug information about the current server + associated player is existent to figure out what might be wrong

**Comment by napstr** [comment]
What kind of information are you looking for exactly?

There are a bunch of lesser known debug commands around, maybe some of them have the info you are looking for? try: `;;adebug` and `;;playerdebug`

**Comment by napstr** [comment]
I just noticed `;;playerdebug` is bot owner restricted. Here is the output I get from my selfhosted one: https://hastebin.com/jexapexavu
Is that the info you are looking for?
We could move that to be admin restricted with @Frederikam's approval.

**Comment by Nanabell** [comment]
hmm ye that is mostly what im looking for. i assume the id is the id of the channel ?

**Comment by napstr** [comment]
it's the guild id

**Comment by Frederikam** [comment]
IIRC this command only spits out information about the current shard, I have no problem making this admin restricted.

**Comment by Frederikam** [comment]
What I imagine is this (in no particular order):

1. Queue size
2. Voice channel
3. Guild
4. Whether or not we have relevant permissions in relevant places
5. The values from ;;adebug
6. List of users in the VC
7. Pause, shuffle, repeat

**Comment by Nanabell** [comment]
I played around with some formatting and this is the basic design I came up with
![image](https://user-images.githubusercontent.com/13600006/31064570-e1362676-a73d-11e7-8088-d351cd0fbbce.png)
thoughts ? am I missing something ? too much information?

**Comment by Frederikam** [comment]
![image](https://user-images.githubusercontent.com/2582617/31069943-dcdd94f8-a75e-11e7-9a9c-4864a49c224b.png)
This doesn't work with LavaLink

**Comment by Nanabell** [comment]
so just drop that info for now? or is there a "correct" way to grab this info now

**Comment by napstr** [comment]
What are the exact permissions used to calculate the checks and crosses?

**Comment by Frederikam** [comment]
`Link#state` would be nice to have. I might want to write a getter

**Comment by Nanabell** [comment]
for the text channels `channel.canTalk()`
and voice channels
```java
if (channel.getGuild().getSelfMember().hasPermission(channel, Permission.VOICE_CONNECT)
    && channel.getGuild().getSelfMember().hasPermission(channel, Permission.VOICE_SPEAK))
```

**Comment by napstr** [comment]
Ok, that's reasonable. I'm suspicious about JDAs permission management though, so don't be surprised if this is not perfectly correct.

**Comment by Nanabell** [comment]
This is bot admin limited command anyways it's just for us to see if ppl are stupid again. you can provide a guildId and will get information for that guild `<<debug guildid`

**Comment by Frederikam** [comment]
Why not make it `DJ` and have it default to the local guild, but for the sake of privacy have it be `BOT_ADMIN` when a guild id is specified?

**Comment by Nanabell** [comment]
seems fine to me. also let me open a pr so we all can see what code i mashed together at 5 in the morning

**Comment by napstr** [comment]
#334 resolves this

**Comment by napstr** [comment]
Btw, after talking with @Nanabell we decided to change the Permission Level to `ADMIN` since the command may expose secret channels and DJ is not an appropriate level for that.
