### ISSUE TITLE
Fredboat Admin Restricted Command to Reset / Clear a player for a Guild

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#184]
I've seen it quite a few times that fredboat is stuck in a vc while it says that its not and ;;join does not help im assuming this can be fixed by destroying the current player associated to the guild

**Comment by Frederikam** [comment]
Mods in guilds can now do ;;destroy as opposed to ;;stop. Is this issue still needed?

**Comment by Nanabell** [comment]
i was thinking about a ;;destroy [guildId] to remotly destroy a player but in hindsight it doesnt seem to be necessary. Other if maybe no mod is online and a user reports these issues to us but i dont see that happening to ofen and then we can join the server ourself and destroy it

**Comment by Frederikam** [comment]
But then the problem is that you're going to have to ask the user for their server ID. Might as well just get them to use a command.

**Comment by Nanabell** [comment]
Yes also part of the reason why i decided against it
