### ISSUE TITLE
Add ;;seek function to ;;play

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#186]
![image](https://cloud.githubusercontent.com/assets/13600006/26549872/6bd016dc-447b-11e7-869d-da1ce338c08b.png)

**Comment by Nanabell** [comment]
the fist one  suggestion (&t=...) is likely a Lavaplayer thing but we could implement the second one. Just wanna hear your thoughts. Im on neither side atm

**Comment by Frederikam** [comment]
This has already been decided against. It isn't very obvious
