### ISSUE TITLE
;;skip command should have a cooldown

### ISSUE THREAD

**Issue by Paulloz** [Frederikam/FredBoat#189]
Hi there!  
We just had a dumb issue while using FredBoat: two users sent a `;;skip` command almost at the same time so (obviously) two tracks were skipped.  
Maybe there should be some sort of mechanism preventing `;;skip` commands within a few seconds from one another to execute?

**Comment by Frederikam** [comment]
Never encountered this problem before, but I can see how it could be useful. Maybe a new contributor could handle this as it's a low-hanging apple.

**Comment by drdgvhbh** [comment]
im gonna try working on this issue.
