### ISSUE TITLE
prevent some channel from playing a music ?

### ISSUE THREAD

**Issue by HadyKamil** [Frederikam/FredBoat#19]
Hi, 

I've really love your work there, i hope you would make a feature to prevent music in some channel, because everyone in my server is spamming music request on #GeneralDiscussion

**Comment by Frederikam** [comment]
Hello,

I recently pushed a change (not sure if working 100%) that allows you to restrict which text channels you can use music commands in. The music bot *should* ignore any music commands from channels it can't send messages in.

Hope that helps.

**Comment by HadyKamil** [comment]
Hi Frederikam, then may i know what is the command for that feature ?

**Comment by Frederikam** [comment]
There is no command. These are Discord permissions. Simply make sure to restrict the music bot from posting in the voice channels, the same way you would restrict a user from sending messages.
