### ISSUE TITLE
Avoid bot leaving when no users on the channel

### ISSUE THREAD

**Issue by Cuchi28707** [Frederikam/FredBoat#194]

**Comment by napstr** [comment]
It's not a bug, it's a feature to save resources.

**Comment by RealKC** [comment]
It could be done for selfhosted bots tho(if it can't be done already), maybe with a config option?

**Comment by Cuchi28707** [comment]
Can I change it in my server?

**Comment by RealKC** [comment]
No cuchi, it's not something you can change ATM, and that's not likely to change on the Public bot

**Comment by napstr** [comment]
You can get the Patron FredBoat which doesn't leave the channel.
https://www.patreon.com/fredboat
