### ISSUE TITLE
Avoid bot leaving channel when no users on it (on my self-hosted server)

### ISSUE THREAD

**Issue by Cuchi28707** [Frederikam/FredBoat#196]
Crash when patron: true

My config.yaml: https://pastebin.com/eMUyb0aa

Crash after enabling patron: https://pastebin.com/cRwBjNgp

**Comment by Frederikam** [comment]
A misconfiguration on your part. Check your credentials

**Comment by napstr** [comment]
Please follow the existing guide on setting up your bot: https://docs.fredboat.com/selfhosting
It covers what you need to do to set it up as patron.

**Comment by Cuchi28707** [comment]
Only happens when I enable patron?

**Comment by Cuchi28707** [comment]
I configured like that, but I don't know what to put in production, music and patron fields
