### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#198]
# Permissions system
I am writing this to myself just to create an outline and to discuss ideas. I want to go for a simple permission system with 3 tiers:

* 3: Admin
*Can change FredBoat configuration and edit permissions*

* 2: DJ
*Can skip, can pause/unpause, can change repeat mode, can change shuffle mode, etc*

* 1: User
*Can add tracks to the queue*

_**TBD: Who controls voteskipping?**_

### Special notes
- Administrators and owners implicitly have all perms
- Permissions are for the entire `Guild`
- Higher ranks have lower rank permissions
- Permissions can be granted to users or roles

**Please give me ideas for better names for these**

## Proposed commands
;;admin list
;;admin add <name>
;;admin remove|del <name>

Note that `admin` can be replaced by `dj` and `user`.

## Checklist
- [x] Set up JPA entities
- [x] Create `PermsUtil`. Named like this to avoid confusion with JDA's `PermissionsUtil`
- [x] Create these commands
- [x] Implement the perms system into the other commands
- [x] Do I18n and upload to Crowdin
- [x] Write documentation (help wanted)
- [x] Testing
- [x] Branch merge
- [x] Announce and deploy

**Comment by Nanabell** [comment]
> 3: Admin

I'm not so sure about naming this Admins, it can be easily confused with the Discord Admin Permissions, while that permission gives you Fredboat "Admin" permission i don't think we should use the same name.
Furthermore we have "Admin restricted commands" but those admins are the users in the config.
I can't come up with a better distinct name right now but its just some food for thought.

> 2: Queue manager

I like the name Queue manager!

> 1: User
Can add tracks to the queue

I assume a user can skip their own songs ?

> TBD: Who controls voteskipping?

What exactly do you mean by "control", if you mean change the way the vote skipping works then its definitely a "Admin" permission since its changing configurations.

> Higher ranks have lower rank permissions

Or in general the whole permission system, imo the whole system should be integrated with the current permissions we have. I.E the "Admin" and "Owner" restricted commands. The simplest way would be to just `enum` the whole thing up to `Botowner` and when a any user tries to execute a command he gets a value for a "rank" and nr needs to be higher or equals to the requirement for the command.
> Higher ranks have lower rank permissions

that would also solve this

My proposal for the enum would be something like this 
```
BLOCKED,
PRIVATE, (maybe?)
USER,
MANAGER,
ADMIN, (still needs a better name)
MASTER, (maybe a better name to distinct global admins from local)
OWNER 
```
I dont't know how the current perm system works we have it might be that we already use this kind of system or we simply don't want anything like this its just my proposal.

> Note that `admin` can be replaced by `manager` and `user.`
  

Do we need to be able to add/remove someone to/from the user list ? Essentially everyone is a user.

**Comment by Frederikam** [comment]
Not everyone is a user. Admins will also have the ability to stop people from being able to add songs alltogether. 

>What exactly do you mean by "control", if you mean change the way the vote skipping works then its definitely a "Admin" permission since its changing configurations.

Eg who can voteskip at all

**Comment by Nanabell** [comment]
> Not everyone is a user. Admins will also have the ability to stop people from being able to add songs alltogether.

I see, but the command ;;user remove seems a bit misleading maybe more like a blocked list ? which would also tie in with the `BLOCKED` enum 

> Eg who can voteskip at all

who can voteskip ? i mean Users should be forced to use the voteskip while queue manager and above have the option to use the normal skip function. but maybe that can be a config option to toggle ? to enable / disable voteskipping

**Comment by Shredder121** [comment]
> I'm not so sure about naming this Admins, it can be easily confused with the Discord Admin Permissions, while that permission gives you Fredboat "Admin" permission i don't think we should use the same name.
> Furthermore we have "Admin restricted commands" but those admins are the users in the config.
> I can't come up with a better distinct name right now but its just some food for thought.

Cheesy suggestion, but who knows it might work: ship crew analogies?
I do agree though, to not use the same names.

**Comment by Almighty-Alpaca** [comment]
Suggestion: rename "Queue manager" to "DJ", sounds better and clearer

**Comment by Frederikam** [comment]
Ehh, you're probably right

**Comment by Frederikam** [comment]
Still need a better name to replace `user`

**Comment by Frederikam** [comment]
**Should we consider everyone with a Bot Commander role to be admins?**

**Comment by Nanabell** [comment]
I would be against it. Many other bots use the "Bot Commander" Role and it might give False Positives. I.e a User has the Role for another bot but now has admins perms over Fredboat aswell. We have a command to give users admin perms. If we still want to go the Role route we can use unique Role Ids to prevent unwanted conflicts

**Comment by RealKC** [comment]
Shredder said we could use ship crew anallogies, so why not use a role like `Quartermaster` for the FredBoat Admin role?

**Comment by Nanabell** [comment]
i would restrain from using abstract definitions for our roles. It will only cause confusion and in the end we will keep answering the same questions

**Comment by RealKC** [comment]
I guess, I was thinking of "FredBoat Admin" but that could cause confusion as well. "Bot Admin" maybe?

**Comment by Frederikam** [comment]
Meet some of the `BOT_ADMIN`s 
![image](https://user-images.githubusercontent.com/2582617/27518254-ea844a0a-59db-11e7-9458-3085625ea0b1.png)

**Comment by napstr** [comment]
oi

**Comment by Shredder121** [comment]
oi noice

**Comment by RealKC** [comment]
oi nice indeed

**Comment by Frederikam** [comment]
This feature should now be completed. I just need to do some testing to make sure it works as intended.

**Comment by RealKC** [comment]
That was fast IMO.

**Comment by Frederikam** [comment]
Wakatime tells me this was about 8 hours of development in 2 days

¯\\\_(ツ)\_/¯

**Comment by Frederikam** [comment]
Maybe a little too early to say that 
![image](https://user-images.githubusercontent.com/2582617/27562455-f2491314-5acc-11e7-9b99-d428a5c0b983.png)

**Comment by RealKC** [comment]
rip

**Comment by Frederikam** [comment]
Draft documentation now available https://docs.fredboat.com/permissions

**Comment by RealKC** [comment]
Docs look good. 👌

**Comment by Shredder121** [comment]
Do we want to mention "Admin" though?

I know there is still not a good alternative.
Maybe something like 'operator'?
(-Owner)
-Operator
-DJ
-User (?)
-Base

If we can't find a suitable alternative, then we'll have to stick with the status quo.

**Comment by Frederikam** [comment]
Why is "Admin" a bad name though?

**Comment by Shredder121** [comment]
> I'm not so sure about naming this Admins, it can be easily confused with the Discord Admin Permissions, while that permission gives you Fredboat "Admin" permission i don't think we should use the same name.
> Furthermore we have "Admin restricted commands" but those admins are the users in the config.
> I can't come up with a better distinct name right now but its just some food for thought.

I am merely observing that this wasn't addressed yet.
Not much else.

**Comment by Frederikam** [comment]
We're probably fine about that. I'm more worried about "USER".

**Comment by Nanabell** [comment]
What is with "BASE" ? if someone is blocked so he cant use commands it shows "BASE" ? that seems also a bit strange

**Comment by Frederikam** [comment]
Not blocked, some commands don't require permissions at all. Blocked would
be misleading.

**Comment by Nanabell** [comment]
i see

**Comment by Frederikam** [comment]
Any requests before I merge this feature branch?

**Comment by Nanabell** [comment]
so we leave USER as it is ?

**Comment by Shredder121** [comment]
how many people have tested it?
just wondering

**Comment by Frederikam** [comment]
>how many people have tested it?
>just wondering
Myself

**Comment by RealKC** [comment]
Myself is not a number, facepalm /s

**Comment by Frederikam** [comment]
Now merged onto development

**Comment by RealKC** [comment]
So time to move to `Done` or will you go directly to `Deployed and announced`(whenever you'll update FredBoat next)?

**Comment by Frederikam** [comment]
I don't intend to update it yet

**Comment by napstr** [comment]
This was announced and deployed to all boats yesterday. Good work!
