### ISSUE TITLE
[;;repeat all] Known bugs

### ISSUE THREAD

**Issue by ObeIisk** [Frederikam/FredBoat#199]
- `;;destroy` does not actually clear the queue (note sure if it even "resets" the player) when the list is on repeat
**`;;destroy` is supposed to clear the queue, no matter if repeated or not.**

- `;;repeat all` `;;skip n-m` will remove the songs from the list, but saying `;;skip` will keep them
**`;;skip` is supposed to remove the songs from the list.**

**Comment by Shredder121** [comment]
> ;;skip is supposed to remove the songs from the list.

I understand the thought behind skip, but when I have a playlist on repeat, I want to be able to navigate inside the queue without losing tracks.
Should I open another issue for this?

**Comment by Frederikam** [comment]
>I understand the thought behind skip, but when I have a playlist on repeat, I want to be able to navigate inside the queue without losing tracks.

You could do something like `;;fwd 50:00:00`

**Comment by Nanabell** [comment]
> You could do something like ;;fwd 50:00:00

that is kinda meh as user experience

**Comment by Frederikam** [comment]
It's not a common use case though

**Comment by napstr** [comment]
Currently forwarding over the track length will do the same as skipping the track, however I'm adjusting it to be treated as not a skip (similar to how split tracks ending is handled), so that behavior will look like what Fred describes in this thread.

**Comment by napstr** [comment]
This was done with the refactoring of the music stack that took place last week following the lavalink deploy.
