### ISSUE TITLE
Fix some data methods

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#201]
```
FredBoat#getAllGuilds
FredBoat#getAllUsersAsMap
```
Are probably horribly inefficient(ly used for counting).
Making this an issue because fixing this might take a few restarts to check if and how alternative implementations are better.

**Comment by Frederikam** [comment]
We usually just need this for the sake of getting the count. We can just cache those numbers.

**Comment by napstr** [comment]
df728aba3beabd5fd485ba9c08f357b3f424c69c

Lets see how that stacks up in production.

**Comment by Shredder121** [comment]
Can I claim this one?

**Comment by Shredder121** [comment]
(If no one wants to do it)

**Comment by Frederikam** [comment]
Go ahead. May I suggest putting this in a separate class? Maybe also do a feature flag for the old system, just in case.

**Comment by napstr** [comment]
Hm. Couldn't assign you but sure go ahead.

**Comment by Shredder121** [comment]
I'm _but_ a contributor
I'm fairly sure you can only assign Collaborators
Oh and Owners

**Comment by napstr** [comment]
Things are workingagain. 978a9368e6df96c7b8a342f6b027f6ad0842ef44 patches the last issue.

**Comment by Shredder121** [comment]
Nice nice
