### ISSUE TITLE
Revamp fredboat.com

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#206]
## Revamp fredboat.com
fredboat.com was so hideous that I ended up just redirecting all traffic to docs.fredboat.com. Ideally, I want to create a web dashboard. Before this we should have a front page.

### Requirements
1. Links to the docs, FredBoat Hangout, and the bot invite link
2. The invite link should redirect to fredboat.com where the user will be greeted by a success page, with docs on what to do next
3. Display an array of features we have
4. Responsive styling for mobile support

**Comment by Frederikam** [comment]
I might just move docs.fredboat.com to fredboat.com/docs/. That would make for some nice common elements like header and footer.

**Comment by Macley-Kun** [comment]
Can i perhaps help with making an improved version for selfhosting + systemd?
Bin working with selfhosting for a while. I have experience working with users and making clear step by step instructions.

I do have to say i'm more familiar writing it in Office Word and then one of you can copy paste it in the website? I'll make sure to cover all the supported OS's to install the necessary components.

**Comment by Frederikam** [comment]
That's pretty unrelated to this issue, but we're also interested in refreshing the selfhosting pages. Specifically we want to remove the compile instructions in favour of providing downloads from our CI server.

The website content is written in [Markdown](https://en.wikipedia.org/wiki/Markdown)

**Comment by Macley-Kun** [comment]
Aaah ic, so the whole need of compiling wouldn't be a thing anymore. Well it was just a suggestion ;)
