### ISSUE TITLE
[Discussion] Make FredBoat Scale

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#208]
### **Update**: Read the discussion below the OP for more info.

The Bootloader is very underrated. We can use it for some neat things.
I want it to be able to start a second (updated for example) FredBoat jar in the background (not reacting to commands) and switch over the running FredBoat to the new one shard by shard.
The benefit of almost seamless updates alone would make this worth implementing.

- [ ] Allow a "ghost mode" that can be turned on, or shards started with, where they are up and running, but don't react to commands

- [ ] Allow some kind of communication between the Bootloader and the FredBoats that it runs, to coordinate shards getting turned on and off

- [ ] Shards need to keep all stateful information (playlists, player settings, temporary listeners, feature flags) in the database, or have a way to transfer it to the bootloader and/or the other running FredBoat

- [ ] Some kind of central authority to coordinate bootloaders on more than one machine

- [ ] Optional: Find a way to grow the shard size in this kind of "no hard restart" mode

**Comment by Frederikam** [comment]
What about orchestration across multiple machines?

**Comment by napstr** [comment]
That can be added on top of those things. I'll add it as a point.

**Comment by napstr** [comment]
Thinking of it like this currently:

layer 0:
Central authority that decides how many shards have to run on which machine (this might be as plain as a discord channel where all bootloaders chill in, receiving commands by the admins)


layer 1:
one Bootloader service per machine that runs the FredBoat jar and handles updating it and reports the status of itself and the shards it manages back to the central authority.


layer 2:
Several shards running inside a JVM.

**Comment by napstr** [comment]
I imagine this could be close to what you wrote up in that docker branch.
I don't know docker good enough, I'm not sure if we get fine grained control over what each shard does with it. Maybe we do. Having each docker container talk to the central authority directly and starting/shutting down/ghosting shards could be a thing.

**Comment by napstr** [comment]
Updating this issue with some more ramblings.
The proposed changes above, utilizing the bootloader, don't scale well, as they use up logins. 

There are at least two other, better ways to achieve smooth updates without using up logins.

Take the JDA route: The crazy one
The goal is to achieve a session resume between two different JDAs. I suppose they would need to run on the same machine so that the IP stays the same from Discord's point of view. To be able to resume, we need to transfer JDA's cache from one to another, this could be achieved by abstracting the cache away in JDA and providing an alternative external implementation (based on Redis for example, maybe ehcache). Then there would be a mechanism needed to plug in this cache and any other session information into a fresh JDA object in another JVM.
Cons: If changes need to be done to the cache (discord introduces new stuff), they likely break the handing over of it. Also a ton:tm: of work. I like to add that my knowledge of websockets does not go deep enough to guarantee this route can even work. 

Take the FredBoat route A: Configurable Commands
A way to plug in commands into the running JVM. I think golang (?) can do that, or maybe some class loader abuse. 

Take the FredBoat route B: Make it a Threeway
Splitting off the Audio playing to lavalink looks like a great success. Take the next step and split FredBoat further up into an event receiving part with JDA that does barely more than parse commands and _maybe_ check against FredBoats permission system and blacklist, and another part containing all the logic.
We would glue these together with a message/job queue of some kind (either postgres or a dedicated one like RabbitMQ maybe?), a message/job could look similar to the newly introduced CommandContext, providing convenience callbacks to the source shard.

**Comment by Frederikam** [comment]
This issue has become outdated with our current vision of FredBoat's future. These issues will mostly be solved in a different manner with Dike.
