### ISSUE TITLE
Expand the FAQ section

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#21]
If you've been hanging out in FredBoat Hangout you might have noticed that people have a lot of questions that aren't already answered in the FAQ in the [docs](https://fredboat.com/docs/faq). Please help answering more questions in the FAQ by sending a pull request on [faq.md](https://github.com/FredBoat/fredboat.com/blob/master/public/markdown/faq.md).

**Comment by Frederikam** [comment]
This could still use some attention

**Comment by napstr** [comment]
[Updated the FAQ with the help of Ternunda](https://github.com/FredBoat/fredboat.com/commit/33629d01c79e966ad68186aa613fca0fd4bd5593)

Adjusted the links in the initial post of this issue since they were dead/outdated.

**Comment by Macley-Kun** [comment]
Update on this? Looks like it's completed 👍
