### ISSUE TITLE
Reason system for the ;;hardban, ;;softban, and ;;kick

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#216]
The Reason format should be liked this:
>Action issued by User#0000(ID: ). Reason: 

The reason should be included after the mention, if a reason is not mentioned, a default reason should be used: "The issuer of the action did not specify a reason. Please contact them!". Of course this will need i18n.

**Comment by napstr** [comment]
Not sure about what you are describing here.

How about just adding a Reason to the current output instead of completely changing it?

![image](https://user-images.githubusercontent.com/6048348/27809359-2b93a120-604f-11e7-8327-a4e783a40b6e.png)

**Comment by RealKC** [comment]
I meant in the audit logs, I'd think it's possible?

**Comment by Nanabell** [comment]
audit logs api endpoint is not documented yet if jda has it its either from the py lib or self reverse engineered

**Comment by napstr** [comment]
JDA has it working. Reasons needs to be max 512 characters is what I found out so far.

**Comment by Nanabell** [comment]
i only see the use for the softban since using the discord ban feature is better in every way

**Comment by napstr** [comment]
Too late, code is almost done ¯\_(ツ)_/¯
Also I'm gonna find a way and to stop those three commands from being major copy pasta and have them at one place.

**Comment by napstr** [comment]
3b1df3a58fbccb7d086f1b7e45640b5dd462e0d5 does this.
