### ISSUE TITLE
Unbox <links> for ;;play

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#219]
When using play like this: `;;play <https://www.youtube.com/watch?v=whatever>` (the <> boxing tells discord to not embed a link) a search happens.
Changing this to directly playing the link is probably better UX.

**Comment by vince21298** [comment]
Hi. I am new to the open source community and will be my first contribution. I want to take a crack at the problem. Thank you.

**Comment by napstr** [comment]
Sure thing. If you have questions about settings things up for development or want to discuss code stuff, make sure to join our discord https://discord.gg/ZWNr7G8 and poke an admin for access to the `#coding` channel.
