### ISSUE TITLE
Make ;;nowplaying display the current time and the full length of the current song

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#22]
The ;;nowplaying command should not only display which song is being played but also how much has been played of it compared to the full length. Perhaps even show the URL to the song. Other ideas welcome.

Currently only the name of the song is being displayed.

![image](https://cloud.githubusercontent.com/assets/2582617/18830340/90498900-83e0-11e6-9f77-46aedf85e1c9.png)

**Comment by JJ-The-Hitman** [comment]
`@Override
    public void onInvoke(Guild guild, TextChannel channel, User invoker, Message message, String[] args) {
        GuildPlayer player = PlayerRegistry.get(guild.getId());
        player.setCurrentTC(channel);
        if (player.isPlaying()) {
            channel.sendMessage("Now playing **" + player.getPlayingTrack().getInfo().title + "** ["
                    + TextUtils.formatTime(player.getPlayingTrack().getPosition()) //edit
                    + " / " //edit
                    + TextUtils.formatTime(player.getPlayingTrack().getDuration())
                    + "]");
        } else {
            channel.sendMessage("Not currently playing anything.");
        }
    }`
Wouldn't this do the job? Inside of the NowPlayingCommand Class. by the way I would join NowplayingCommand to The Capital P :D

**Comment by Frederikam** [comment]
Committed. Next time please open a pull request instead of posting your code in a comment.
