### ISSUE TITLE
commands that don't have anything to do with the music part does not work

### ISSUE THREAD

**Issue by Matasmar8** [Frederikam/FredBoat#225]
for example the ;;clean or any other command except for the music commands do not work

**Comment by Frederikam** [comment]
Music commands are disabled when running as a PATRON or MUSIC distribution.
This is intentional, as there is very little demand to selfhost the other
functionality.

**Comment by napstr** [comment]
Run the bot as the Development distribution to enjoy patron benefits and all commands.
The [selfhosting docs](https://fredboat.com/docs/selfhosting) explain which config options you need to set for that.
