### ISSUE TITLE
BOT_ADMIN not overriding manage messages on ;;destroy

### ISSUE THREAD

**Issue by MasterMapMaker** [Frederikam/FredBoat#231]
More or less what the title says, BOT_ADMIN cannot use ;;destroy without having a role for manage messages, I don't know if the requirement should be lifted, or if that requirement should stay, but be bypassed for BOT_ADMIN

**Comment by RealKC** [comment]
My comment on issue #144? I initially wanted to make an issue about this, but remembered that issue and commented there.

**Comment by Nanabell** [comment]
that issue was from before the implementation of the permission system and your comment doesnt really make clear what you mean having this as its own issue is fine as is

**Comment by Frederikam** [comment]
Able to reproduce 
![image](https://user-images.githubusercontent.com/2582617/28818946-e9cd506e-76ac-11e7-81b6-76e768a170ba.png)
