### ISSUE TITLE
Send ;;commands output as a DM

### ISSUE THREAD

**Issue by AndrielChaoti** [Frederikam/FredBoat#232]
Instead of spamming a huge wall of text in a chat channel like the ;;help command does not, I would like to see the ;;commands command also do this. This would be doubly useful for both the regular and music boats.

**Comment by napstr** [comment]
Please explain why this should be the desired behavior.

**Comment by Vandesdelca32** [comment]
In my, and our server's experience, the output of the `;;music` command can get a little spammy in that channel. In our instance it is desired, to remove the giant wall of text that command unfortunately is, and make it somewhere not so obvious.

I am sure there are other ways of doing this that are equally or even more valid, it is just our solution to a problem we saw.
(for reference, the output scrolls of the top of the screen, with nothing else there)

**Comment by napstr** [comment]
What do you mean by "spammy"? If you have users abusing that command you need to moderate them, not change the behaviour of a command that is perfectly fine for the majority of non-abusive users.

**Comment by Vandesdelca32** [comment]
We run a fairly large public server, but that is also true. I'm happy to keep the changes to myself if we don't want to make it default behaviour.

**Comment by napstr** [comment]
What about introducing a cooldown for it?

**Comment by Vandesdelca32** [comment]
that could also work... I did it this way originally because that's what I was asked to do

**Comment by napstr** [comment]
Implemented by #233
