### ISSUE TITLE
Add .mp3 support for selfhosted bots

### ISSUE THREAD

**Issue by Headhunterzpw** [Frederikam/FredBoat#238]
Hi,

I want to give a suggestion for playing .mp3 files for the selfhosted bots but I acknowledge the risks of getting DDoSS'd but still I like this option since I've got a server where I'm hosting my .mp3 files for the minecraft server which is related to the server

**Comment by Frederikam** [comment]
It is not really intentional that selfhosters should be without HTTP(S). We intended to use a proxy to get around the vulnerability, but that proved to be very difficult.
I will label this as a bug. For now you should be able to run the following command to temporarily add support:
```js
;;meval pm.registerSourceManager(new com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager());```

**Comment by napstr** [comment]
#242 solves this
