### ISSUE TITLE
Make ;;queue also show track length

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#247]
I think the title is pretty self-explanatory.

**Comment by csimoncelli** [comment]
Hello!  @RealKC @Frederikam @Nanabell 

New to GitHub here.  With your permission, I'd like to take advantage of the beginner nature of this issue and give a shot at resolving it, although I do have some questions before anything else:

- Are there due dates to issues like these?
- Who can I contact (and how) should I need assistance?
- What are some first steps to get started?

Thanks in advance!  Looking forward to trying this out.

**Comment by Nanabell** [comment]
okay im kinda sorry for this, but ive done this issues already but im gonna answer your questions anyways
>Are there due dates to issues like these?  

No there is no due date on any of our issues, if an issue is really urgent we likely dont even create a github issue and just fix it 
>Who can I contact (and how) should I need assistance?

Feel free to join our [discord](https://discordapp.com/invite/au2cDVY) server and ask any Staff member for the "Coder" role to get access to the #coding channel 
>What are some first steps to get started?

to get started i would suggest you head over to our [docs](https://fredboat.com/docs/selfhosting) and try to set up an enviroment to selfhost the bot you'll need git, maven and java.   
Get yourself an ide like [IntelliJ IDEA](https://www.jetbrains.com/idea/).  
If you have any questions at all like i said feel free to join our discord server

**Comment by csimoncelli** [comment]
No problem at all!  Thanks for the heads up here and for all the advice.  I'll take a browse around and see if there's anything else I can pickup.
