### ISSUE TITLE
HttpAudioSourceManager as FeatureFlag ?

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#248]
like the title says, if you want to re-enable the HttpAudioSourceManager you have to undo aacb2e7d48b8b88c7376d86ae0541eb6cb19a161.  
 While this works it's a bit awkward. So my proposal would be to make the HttpAudioSourceManager a Feature_Flag.

EDIT:
just saw this kinda ties in with #242 gonna leave this open through until we merge it into master so we don't forget

**Comment by Frederikam** [comment]
The PR will serve as a better reminder
