### ISSUE TITLE
Doc Information about Nodes/LavaPlayer Nodes

### ISSUE THREAD

**Issue by majorcyto** [Frederikam/FredBoat#251]
Hi,

I am self-hosting the bot on one of my bot servers for our music player and it works great. Also, it is the highest quality music bot I have tried so far, I tried 5 self-hosted ones before this one.

I noticed when it starts up it mentions nodes, and lava player nodes but I do not see any information about it in the docs or the self-host section.

Would you be able to shed some light on these functions?

**Comment by Frederikam** [comment]
Lavaplayer nodes allow FredBoat to have remote server process audio. There's no need for this if you have a small bot.

**Comment by majorcyto** [comment]
You are right in that I don't necessarily _need_ it. But, I was still hoping to learn about it.

**Comment by napstr** [comment]
[Lavaplayer nodes documentation](https://github.com/sedmelluq/lavaplayer#load-balancing) + reverse engineering FredBoat's Config.java file should help you figure out things.

**Comment by Frederikam** [comment]
~~So basically, FredBoat requires a library called Lavaplayer that processes audio so it is ready to be sent to Discord. This requires a good amount of CPU, so this process can then be outsourced with what's called a Lavaplayer-Node.~~

~~But even then, it is not very scalable. Lavaplayer is fundamentally flawed as it needs to send the audio back...~~

Ninja'd

**Comment by napstr** [comment]
Yeah, I think the important part here is, that we are about to move away from them (not even sure we are using them in production currently). There is no point in writing a documentation for them.

**Comment by majorcyto** [comment]
Ah I see! I did find your other implementation you are working on (Lavalink) which I am guessing is supposed to be an optimized successor? Thank you for the information, I will read those docs, and also follow LavaLink.

I just enjoy learning all the things. Thanks for answering!

**Comment by Frederikam** [comment]
>not even sure we are using them in production currently

We're not

**Comment by majorcyto** [comment]
While I am in here, how do the nodes/shards work for the bot itself, or is that still related to Lava? I noticed the nodes command which is empty when ran. Or the shards, which just says 1/1 since I only have the one.

**Comment by Frederikam** [comment]
Shards and lavaplayer nodes are completely different things. For shards see https://discordapp.com/developers/docs/topics/gateway#sharding

**Comment by majorcyto** [comment]
Oo I see, so it is like load balancing for the bot then.

**Comment by Frederikam** [comment]
If it wasn't for the fact that we had all shards on the same machine

**Comment by majorcyto** [comment]
Will it auto-shard if it detects other ones running on the same machine...?

**Comment by Frederikam** [comment]
No

**Comment by majorcyto** [comment]
I trudged through the actual files, it looks like a config option that is not listed?

**Comment by Frederikam** [comment]
Which option?

**Comment by majorcyto** [comment]
Well it took me a while, but I got JDA/OAuth and Sharding to work. I also force tested 5 shards and initialized it for the main bot and music and it worked great. This is really neat.

I really want to play with the lava nodes. But I guess there isn't a point if you are going to introduce LavaLink soon. Or is Lava Link already set up to work with the existing Lava implementation?

**Comment by Frederikam** [comment]
The word `Lava` is ambiguous as it can refer to both. Lavalink and Lavaplayer use different protocols.

Lavalink is working if you get the lavalink branch.

https://ci.fredboat.com/viewLog.html?buildTypeId=FredBoat_Build&buildId=lastSuccessful&buildBranch=refs%2Fheads%2Ffeature%2FLavalink
https://ci.fredboat.com/viewLog.html?buildTypeId=Lavalink_Build&buildId=lastSuccessful

**Comment by majorcyto** [comment]
Nice! I don't know why I didn't check the branch list lol. So I see you connect it via url/password. But how do you run the actual lava link itself. Do you put the bot into lava link mode, or is lava link a separate compiled program.

Thank you for putting up with my dumb questions. lol

**Comment by majorcyto** [comment]
Oh, run this guy? https://github.com/Frederikam/Lavalink

**Comment by Frederikam** [comment]
Yes, the second link I just sent leads to the latest build of Lavalink-Server

**Comment by majorcyto** [comment]
Nice, I see it now in the Artifacts. Will try this out now, thanks!

**Comment by majorcyto** [comment]
What should the format be for the credential file? I see it is an array, but I am having trouble visualizing how to set it up. I got the lava link server running on a separate server node. Compiled the lava link branch for the bot. Just need to figure out the config set up for the Lava Link.

**Comment by Frederikam** [comment]
```yaml
lavalinkHosts:
  "ws://localhost": "youshallnotpass"
```

**Comment by majorcyto** [comment]
Nice, it worked! I tested it and it played music from the Lava Link. This is awesome, thanks for answering all of these questions for me.
