### ISSUE TITLE
[CONTRIBUTING.md] Code Style Conventions + Setting up the IDE

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#252]
What about adding some super lazy code style conventions to CONTRIBUTING.md in the form of:

- Please use the default Intellij IDEA code formatter
- Only adjustment: Don't wildcard imports
<link to xml file hosted on fred.moe or something>
optional: SaveActions plugin (make sure to tick "Reformat only changed code")

^ thats what im using and I think its very close to what @Frederikam uses too
Idk about your netbeans thing @Shredder121, can you check whether it supports importing intellij code styles xmls?

Reasons: Writing a lengthy and detailed code conventions explanation is out of scope for this project imo. Providing a convenient formatting file and settings to import for common IDEs will bring contributors on the same page in an easy way.

Further on, I'd like to add a few nifty commands and settings on how to run from the (intellij) IDE in debug mode with maven, hot swapping, etc.

**Comment by Nanabell** [comment]
>Please use the default Intellij IDEA code formatter

makes it sound like if they want to contribute they have to use Intellij

**Comment by napstr** [comment]
Devs using other IDEs should feel free to add code style files for the other IDEs. I know most of us are using Intellij (even got a few licenses for this project), so I see no reason not to share a code style file. It's a straight improvement over the current situation.

**Comment by knight-ryu12** [comment]
IDEA is better

**Comment by Frederikam** [comment]
>Only adjustment: Don't wildcard imports

Can't be bothered about this tbh. IDEA automatically hides the imports anyways

I can't think of any differences in formatting between IDEA and NB besides the wildcard imports.

**Comment by Shredder121** [comment]
> I can't think of any differences in formatting between IDEA and NB besides the wildcard imports.

The ordering, but I can add a formatter configuration.

**Comment by napstr** [comment]
> Can't be bothered about this tbh. IDEA automatically hides the imports anyways

That's exactly the reason why there's no need to wildcard them (I don't even know what wildcards are for? They seem to be about shortening the list of imports vs potential conflicts and breaking things, which don't really matter with modern IDEs).

Anyways, I decided to just mention to use a default formatter and give an example on how to set things up for IntelliJ.
