### ISSUE TITLE
Event system and a reminder thing

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#253]
Recently an event system has been suggested.

- A way to set the role which will be pinged when the event needs to happen;
- Maybe make it so people can add a picture as a thumbnail;
- I guess fields could be useful for making the actual description less clutered;
- Setting the channel in which FredBoat announces;
- Storing the thing in a DB so it can be pulled later would be nice(also allow events to automatically go at a specific time);
- I guess showing somewhere who created the event and/or who pulled the event at that specific time would be nice.

Can't think of anything else about the event system right now.

Also I guess a reminder thing could appear based on this.

**Comment by Frederikam** [comment]
These are non-trivial features that are out of scope for a music bot.
