### ISSUE TITLE
Weird behaviour of the permission commands

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#256]
![](https://fred.moe/l-1.png)

While the role Admin doesn't exist, the issue happens when a role exists as well.

![](https://fred.moe/GY7.png)

I assume this happens with `;;user` too and with all the subcommands of these commands.

**Comment by Nanabell** [comment]
able to reproduce on lasted dev branch.
`getSearchTerm` in `ArgumentUtil` needs a revisit
![image](https://user-images.githubusercontent.com/13600006/29714530-ee1afd4c-89a3-11e7-9419-b8f6ae6faeb9.png)
`indexOf(args[argsToStrip]` doesnt really work if the same arg appears twice, maybe strip the prefix before getting the Terms ?
