### ISSUE TITLE
Voteskipping

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#26]
Command that skips once a majority has been reached

**Comment by Frederikam** [comment]
The idea is to create a config option to enforce voteskip, while allowing admins to forcefully skip.

**Comment by RealKC** [comment]
Obelisk suggested this:

![](https://fred.moe/yoP.png)

`;;config` should show if `;;voteskip` is enabled or not though.

**Comment by napstr** [comment]
Almost a year lol
