### ISSUE TITLE
Change status/game w/o source edit

### ISSUE THREAD

**Issue by Macley-Kun** [Frederikam/FredBoat#260]
So atm i would edit the source file and don't have to deal with status ever again. Yet i think it's more convient for selfhosters to edit the status/game of their bot trough a command.

Optionele: the ability to add multiple status/games that change every 1 minute or so.

**Comment by napstr** [comment]
Use the eval command.

**Comment by Macley-Kun** [comment]
But that didn't stayed between restarts you just told me?

**Comment by napstr** [comment]
Neither would a command.

**Comment by Macley-Kun** [comment]
Really? But on like other bots (Nadeko) i can change the status/game and it just saves it??? Shouldn't it be possible for FredBoat too then?

**Comment by napstr** [comment]
Not saying that's impossible. It's just a thing someone needs to code. Maybe you're up for that?

**Comment by Macley-Kun** [comment]
Yeh that's why i made the reqeust. But god i can barely code in VBA! That's why i checked in the server if someone already was working on it.

**Comment by napstr** [comment]
There are _a lot_ of issues that come before this one. There is no use case for the hosted FredBoats for this, so I kind of expect the selfhosting community to step up here if they really want such advanced features.

**Comment by Macley-Kun** [comment]
We'll see. I'll leave it open but if someone wants to do it. If it's not ok to keep this open feel free to close. It was just a request :)

**Comment by Frederikam** [comment]
The obvious solution would be to use a config value in configuration.yaml

**Comment by napstr** [comment]
> The obvious solution would be to use a config value in configuration.yaml
ee166d0 does that. This issue goes beyond that.

**Comment by Macley-Kun** [comment]
@napstr ic the request has bin implemented :) ? Can i close this one ^^ ?

**Comment by napstr** [comment]
The request was having a command and an ability to have several statuses rotate, and I don't see that implemented.

Feel free to close this issue if you think what's currently there is enough for you.

**Comment by Macley-Kun** [comment]
oh just changing it to smth like nothing is already good enough for me!
