### ISSUE TITLE
Why is fredboat offline?

### ISSUE THREAD

**Issue by Sammunition** [Frederikam/FredBoat#267]
Why is fredboat offline and how can i get him back online again

**Comment by Nanabell** [comment]
Fredboat is not offline though 🤔 and if it goes offline we will do everything possible to get it back up asap. What you're talking about is likely that a shard went offline which was connected to your guild but these shards come back up on their own so just wait a few minutes.
Feel free to join our [Discord](https://discordapp.com/invite/cgPFW4q) server, if the bot goes down for an extended period of time you will be informed there first
