### ISSUE TITLE
;;skip @user#0000 to skip all of one users added tracks

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#269]
A `DJ` should be able to skip all of the songs of any user by doing `;;skip @user#000`, while a nonDJ should be able to skip of all his songs by doing this, or I guess `;;skip mine`.

Was suggested today in #suggestions.

**Comment by Nanabell** [comment]
Is this supposed to skip all queued tracks of a user?

**Comment by Nanabell** [comment]
while ur at it @Frederikam this can be closed aswell
