### ISSUE TITLE
Create ;;userinfo command

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#27]
Displays info about a user

**Comment by goti921** [comment]
I would like to contribute.
Any More details ?

**Comment by Frederikam** [comment]
@goti921 
First of all, you should read the repo README.md first if you haven't already
You will find that in order to get the bot to run, you will need to provide a bot token in the respective strings in the `credentials.json` file. Create a bot user here:
https://discordapp.com/developers/applications/me

As for what I expect for this command, I would like an output that looks similar to the `;;stats` command. Example values:
* Username
* User ID
* Known nicknames
* Known servers
* User join date
* User creation date
* Avatar URL

Good luck! Feel free to ask questions along the way.
