### ISSUE TITLE
I can't download this...?

### ISSUE THREAD

**Issue by Mindooner** [Frederikam/FredBoat#274]
I've tried a couple of times downloading this but I couldn't. When I tried to download it on github desktop it wouldn't work. When I tried to download it on opera it said "Interrupted Forbidden" Please help.

**Comment by napstr** [comment]
Define "this"

**Comment by Macley-Kun** [comment]
Please provide more info. On which computer your doing this? (Windows/Linux(Ubuntu/Debian/etc). Have your followed the FredBoat guide? https://docs.fredboat.com/selfhosting

It is orientated around Linux. So you might wanna just invite the old trusty public FredBoat :) to avoid any hassle.

**Comment by Macley-Kun** [comment]
@Mindooner ya still have issue bud?
