### ISSUE TITLE
Change command name handling to no longer be case-sensitive

### ISSUE THREAD

**Issue by AndrielChaoti** [Frederikam/FredBoat#278]
Currently, entering in any command in the wrong case, for example `;;Play` will just fail silently in the channel.

It would lend to a better UX if commands were not case-sensitive. (Only the names checking would need to be changed for this, not parsing arguments, as there is reason for those to be case-sensitive.)

**Comment by Macley-Kun** [comment]
I think this one can be closed, seeing that the commitment has taken place successfully :)
