### ISSUE TITLE
Userinfo command doesn't find bots

### ISSUE THREAD

**Issue by Kurozume** [Frederikam/FredBoat#279]
As shown in the screenshot below; when mentionning a bot with `;;userinfo`, the bot returns `no result`, despite the target clearly being in the guild

![](https://i.imgur.com/APZjoG6.png)

_Sent from my Xperia XZ (F8331) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndrielChaoti** [comment]
*is going to try to fix this*
Is there any other commands where the bot should check for bots too?
