### ISSUE TITLE
Create ;;serverinfo command

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#28]
Displays info about a server

**Comment by takoz53** [comment]
Should be displayed as following:

```C#
"Welcome to" + getServername() + ".\n
This Server currently has " + getUserCount() + "User(s).\n
Right now there are / is " + getOnlineUsers()  + "online User(s) in this Server.\n
There are " + getBotCount() + "Bot(s) available.\n
Have fun in the Server!"
```

Would be C# here tho; Convert to Java xD

**Comment by Frederikam** [comment]
FredBoat shouldn't be giving out welcomes unless configured to do so, and I have no plans to make that configurable. I just want to bluntly show stats about a server. Take a look at the ;;stats command, which shows global stats.
