### ISSUE TITLE
Channel Categories bug

### ISSUE THREAD

**Issue by Macley-Kun** [Frederikam/FredBoat#286]
So i made some categories in my Discord server and noticed FredBoat didn't respond. After some testing i found out the channel categories made the bot not able to connect proper. The categories weren't even added to any voice/tekst channel.

In the first two pictures you see that no output is given, and that indeed FredBoat isn't booted proper. I added a time so you can refer it was indeed the categories.

![error 1](https://user-images.githubusercontent.com/26381427/30250652-99f65854-9652-11e7-82d0-5fcbf9a2845c.png)
![error 1 phone](https://user-images.githubusercontent.com/26381427/30250653-9a0c620c-9652-11e7-92a8-f301e49c1616.JPG)

In the next pictures you can see FredBoat working.
![fix 1](https://user-images.githubusercontent.com/26381427/30250674-fbb36d2a-9652-11e7-882f-c40e70342abc.png)
![fix 1 phone](https://user-images.githubusercontent.com/26381427/30250675-fbb474ae-9652-11e7-8544-393be6bec7ad.JPG)

I had this issue also withoud adding emoji's in the categories. The version of FredBoat is around 1 to 2 days old. (last friday).

**Comment by knight-ryu12** [comment]
Need update to latest JDA.

**Comment by Macley-Kun** [comment]
@knight-ryu12 
root@DeltaBot:~# java -version                                                                         
java version "1.8.0_144"                                                                               
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)                                                  
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)   

Are you sure? Because i think java 144 is the latest?

**Comment by knight-ryu12** [comment]
I mean JDA. not JVM

2017/09/11 午前1:13 "Macley-Kun" <notifications@github.com>:

**Comment by knight-ryu12** [comment]
@napstr seems JDA updated to solve this issue

**Comment by napstr** [comment]
Categories just spam the log at this moment, because they were released surprisingly and the discord api lib were using wasn't prepared 100%, they don't break any functionality however.
If you want the error spam gone, update to latest [JDA](https://github.com/DV8FromTheWorld/JDA) (not Java).

**Comment by Macley-Kun** [comment]
Oh wow ok, didn't knew that was a thing, i'll leave this open for a little until i solved the issue ok. Thanks for that link napstr!

**Comment by Macley-Kun** [comment]
Not wanna sound dumb but. I just have to update the fredboat jar file right?

**Comment by Macley-Kun** [comment]
didn't rlly got it fixed but. I just wait with the categories 👍

**Comment by Frederikam** [comment]
https://github.com/Frederikam/FredBoat/commit/aa8009100a0fe38e962d1ff0d343463b2661c4ec
