### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#287]
Just, um, tons of metrics. With a shiny dashboard (Grafana). Reason: Cause we can.
Target Audience: The bot admins. Maybe create a public dashboard in Grafana, but that's an optional goal imo.

Already explored a few things, I think Prometheus is fine to use for it.

A bit more details: Metrics would be exposed in the API under path /metrics, and collected by a remote Prometheus server.

Here's a rough list of things that could be tracked:
Shard connects, disconnects, resumes
Commands received/processed
Messages sent
Active music players
Guild joins / leaves

Other things:
General machine / JVM metrics (Prometheus client comes prebuilt with them with a one-liner)
Hikari and Hibernate metrics (Hikari has their own support, Prometheus has a package for Hibernate)
Logback stats
Postgres stats (? read somewhere about a plugin for postgres or something similar like that)

Feel free to brainstorm your additional metrics ideas.

**Comment by Kurozume** [comment]
Would there be a way to track the number of errors occuring?
May be useful if we want to see which commit / update caused the errors to start appearing so we can troubleshoot

**Comment by napstr** [comment]
Counting errors is pointless if we don't know what they are and where they are happening, that's what #281 should solve with sentry.

**Comment by Nanabell** [comment]
I mean would still make a nice graph

**Comment by napstr** [comment]
The logback stats contain a count of total errors, that should work for a graph :)

**Comment by napstr** [comment]
Keeping this open until we're done building a dashboard.

**Comment by napstr** [comment]
To complete this, a decision on how to expose the metrics endpoint to the scraper needs to be done by @Frederikam

**Comment by napstr** [comment]
Stuff has been deployed, ports firewalled, proxies set up etc - long story short, metrics are finally up and running all the way from collecting in FredBoat over aggregating in Prometheus to displaying in Grafana.
