### ISSUE TITLE
The non-music version is offline.

### ISSUE THREAD

**Issue by EricGit23** [Frederikam/FredBoat#293]
![2017-09-13 6 49 16](https://user-images.githubusercontent.com/26327383/30373574-65bb4c24-9847-11e7-9680-2268ef7c5d10.png)
![2017-09-13 6 50 41](https://user-images.githubusercontent.com/26327383/30373600-7ec420b0-9847-11e7-8e8d-cf26d81b3396.png)
Here is some screenshots from my server.
The commands not working.

**Comment by Nanabell** [comment]
yes, this is known. And from what Fred is working on it doesn't seem like we will be booting it back up as we will merge the nonmusic bot with the music bot

**Comment by Frederikam** [comment]
https://github.com/Frederikam/FredBoat/issues/291
