### ISSUE TITLE
Bot doesn't play direct MP3's anymore

### ISSUE THREAD

**Issue by yellowcooln** [Frederikam/FredBoat#294]
The bot used to be able to play Direct .mp3 links or other media files. Now it doesn't. I've tested this with The patreon bot, development, and standard. 
![discord_2017-09-14_09-11-32](https://user-images.githubusercontent.com/12516003/30431767-aec1d5f0-992d-11e7-98fe-b53937a6bd99.png)

Even using my website It still doesn't play.

**Comment by Frederikam** [comment]
See https://github.com/Frederikam/FredBoat/pull/242

Also make sure your bot is up to date

**Comment by yellowcooln** [comment]
Yes, it is. Using build #794.

**Comment by Macley-Kun** [comment]
@yellowcooln type this in:

.meval pm.registerSourceManager(new com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager());

Then redo that play command. Tell me if it's fixed, then you can close this :3

**Comment by yellowcooln** [comment]
![putty_2017-09-14_10-15-44](https://user-images.githubusercontent.com/12516003/30434614-bed4ffe6-9935-11e7-94f9-0b9b6b2ba5ab.png)

**Comment by Macley-Kun** [comment]
Sorry i ment in Discord itself :P

**Comment by yellowcooln** [comment]
Still didn't work.

**Comment by Macley-Kun** [comment]
You have the latest FredBoat?

**Comment by yellowcooln** [comment]
Okay I figured it out. I had the newest jar file. Just not all the new code that needs to go into the config.yaml

> enableYouTube:     true        # Set to true to enable playing YouTube links
> enableSoundCloud:  true        # Set to true to enable playing SoundCloud links
> enableBandCamp:    true        # Set to true to enable playing BandCamp links
> enableTwitch:      true        # Set to true to enable playing Twitch links
> enableVimeo:       true        # Set to true to enable playing Vimeo links
> enableMixer:       true        # Set to true to enable playing Mixer links
> enableSpotify:     true        # Set to true to enable playing Spotify links
> enableHttp:        true        # Set to true to enable playing direct links

**Comment by Macley-Kun** [comment]
Ah ic, your using an older fredboat. The newer one uses that commando i sendid ya. Have fun listing to .mp3 ;3

**Comment by yellowcooln** [comment]
Thanks. Also noticed that the Public bot can't play MP3's don't know if that is on purpose or not. [https://puu.sh/xzzue/1e40a98e32.png](url)

**Comment by Macley-Kun** [comment]
Yup that's on purpose! Because some security thingie. They are trying to setup a proxy to solve this. Have no update on it sadly :(

**Comment by Nanabell** [comment]
currently we disabled the ability to use direct HTTP(S) streams in the public bot.
This is due to threats of, and actually performing of (D)DoS attacks on bots once the IP address has been revealed.
This unfortunately is a hard problem to solve, so for the time being we've turned it off.
Sorry for the inconvenience.

this is the response we give to users who ask this in our discord

**Comment by yellowcooln** [comment]
I was just typing to ask if IP resolving was the issue. @Nanabell
