### ISSUE TITLE
;;list Embed + liiiinks!

### ISSUE THREAD

**Issue by Macley-Kun** [Frederikam/FredBoat#297]
Hey Fred, are you ok with the idea to only embed ;;list? We should also include the link to the song if people want to listen ot it for themself. The reaction to navigate thing doesn't have to be in it. If you prefer static list.

Ternunda Hunter#1543
The list would just be comprised of the title and that title is a clickable link. Preferrably it wouldn't include the np bit with all the details

Uzume Tennouboshi (ง'̀-'́)ง#4452
So like this
But less of a text wall
https://uzume.s-ul.eu/M1Tf6Bg4.png

RAISE YOUR DONGERS (ง'̀-'́)ง
Maybe toggleable per guild?
Up to Fre_d with that tho

**Comment by Kurozume** [comment]
Will be looking into this at some point in the next few hours (hopefully).
Otherwise I'll be looking at it over the weekend

**Comment by Frederikam** [comment]
The staff has decided to close this issue due to limitations of current embeds. Embeds are simply not wide enough, meaning that song titles get broken into multiple lines. This looks hideous and severely harms readability.

![image](https://user-images.githubusercontent.com/2582617/30498903-ce911ee6-9a58-11e7-99fb-34dd4b4a572f.png)

**Comment by Macley-Kun** [comment]
Sad that iT cant be done. Still happy that we discussed and tried it!

**Comment by Kurozume** [comment]
I will try and revisit this concept at a latter date if I find a way to format the embed better, or if discord would allow us to use the whole chat space and not a small portion of it :/

**Comment by Macley-Kun** [comment]
I could try to ask to the developers if it’s an option to embed the whole width. 

But the link part shouldn’t be an issue withoud embedding right? Atleast half the request can be done right away withoud any hassle :)

**Comment by RealKC** [comment]
The link part can't be done, it's exclusive to embeds.

**Comment by Macley-Kun** [comment]
How about this solution?
https://cdn.discordapp.com/attachments/117523346618318850/358334087817330702/unknown.png

**Comment by Kurozume** [comment]
This was discussed, but we decided that at that point it would be more worth it to just send the list as a regular message rather than an embed

**Comment by RealKC** [comment]
The ;;nowplaying embed already has a clickable title(which sends you to the video on YouTube)

![img](https://fred.moe/cYJ.png)

**Comment by Macley-Kun** [comment]
Mhm ic. Well I would rather have the link then seeing the full title. Because a user is more interested in the music/video then the title itself.

But idk it was suggestion that could help it :p

**Comment by RealKC** [comment]
What do you mean? The has a link under it, it just displays the title.

**Comment by Macley-Kun** [comment]
I mean for in the list command! Now you only see the title, so you gotta google it up, hope ya find the right one blabla.

**Comment by RealKC** [comment]
So you're suggesting replacing the title in the list command with the link? I can tell you reasons why that's not good:
1. if someone queues earrape, you have to click the links to see if they're earrape or not
2. the above but for other type of rulebreaking tracks

**Comment by Kurozume** [comment]
I mean one solution would be to do something like the following:
[!image](https://uzume.s-ul.eu/Kh0YbysS.png)
But in my opinion this does not look good as an output

**Comment by RealKC** [comment]
That does indeed look bad

**Comment by Macley-Kun** [comment]
URL shortener an idea? Or is that gonna blow the google's api up?

**Comment by Kurozume** [comment]
That would blow google's api up
Also Imo having links in the `;;list` command looks ugly all together

**Comment by Macley-Kun** [comment]
true, but idk how else we can solve this in the future. I don't see Discord developers making the embed as long as the chat. They probably have their reasons too 🤔

**Comment by Kurozume** [comment]
Simple; we leave the `;;list` command as it is and people use `;;np` if they want a link to the song when it plays

**Comment by Macley-Kun** [comment]
Agreed, for now (and sadly forever probably) the ;;list command stays what it is :') Perhapes some other music outputs can be embedded withoud any hassle.
