### ISSUE TITLE
Use image links instead of files

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#299]
This is a possible small optimization.
Instead of uploading image files each time, use the image url field of an embed.
That way we outsource the "heavy" lifting of the files to imgur/discord cdns.

**Comment by Shredder121** [comment]
One thing, do we then check for liveliness of the url?
The imgur url *could* be dead between refreshing, and sending it off to discord.

**Comment by napstr** [comment]
How would we do that check in an efficient way?

**Comment by SuhanKoh** [comment]
They supposed to give you status code, https://api.imgur.com/errorhandling

**Comment by napstr** [comment]
That's only viable if the image itself it cached. If each request is going to load it again, it's not worth implementing.

**Comment by Shredder121** [comment]
> One thing, do we then check for liveliness of the url?

Don't get me wrong, "no" is also a perfectly valid answer.
I just wanted to point out, that we will never actually visit the urls, so we never know if the url we send off was a live one or not.
Until we rebuild the album.

We only have to take that into consideration when deciding to do this, and how to do this.
