### ISSUE TITLE
Custom domain Bandcamp

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#304]
This will be recognized: https://circleofdust.bandcamp.com/album/machines-of-our-disgrace-2
But this won't: http://music.businesscasual.biz/album/introspection

Nothing from here will play either: http://music.monstercat.com/album/nerds-by-nature-the-remixes

This might need to be PRed into lavaplayer, not FredBoat.

**Comment by Frederikam** [comment]
This is a Lavaplayer issue
