### ISSUE TITLE
userinfo command error

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#307]
![error](https://user-images.githubusercontent.com/27128153/30734964-49938d7c-9fb8-11e7-8765-b168d09aebc1.png)

How can i fix it

**Comment by Frederikam** [comment]
Did you compile this build yourself or download it from ci.fredboat.com?

**Comment by napstr** [comment]
You are missing the language submodule, you need to git clone the repo recursively. This might be a might be a helpful resource for getting started: https://fredboat.com/docs/selfhosting

**Comment by Frederikam** [comment]
Or at least, it looks out of date. If it was missing they wouldn't have that Korean localization 😛

**Comment by KKHaneul** [comment]
@Frederikam I did compile bot myself to git clone command.

@napstr when i launched git clone command, i definetely saw Language submodule download message. and i can find it /FredBoat/src/main/lang dir.

**Comment by Frederikam** [comment]
Have you ever run `git pull`?

**Comment by KKHaneul** [comment]
@Frederikam Yup

**Comment by KKHaneul** [comment]
![2017-09-23_080403](https://user-images.githubusercontent.com/27128153/30767215-ce5ccf5a-a035-11e7-96e2-bd2020359063.png)

I tried switch language, but same error was occured

**Comment by napstr** [comment]
Update the language submodule.

**Comment by KKHaneul** [comment]
How can i do 😢

**Comment by KKHaneul** [comment]
`root@Haneul:~# git clone --recursive -b development https://github.com/Frederikam/FredBoat.git
Cloning into 'FredBoat'...
remote: Counting objects: 14763, done.
remote: Compressing objects: 100% (280/280), done.
remote: Total 14763 (delta 250), reused 354 (delta 161), pack-reused 14288
Receiving objects: 100% (14763/14763), 5.97 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (8614/8614), done.
Checking connectivity... done.
Submodule 'FredBoat/src/main/resources/lang' (https://github.com/Frederikam/FredBoat-i13n.git) registered for path 'FredBoat/src/main/resources/lang'
Cloning into 'FredBoat/src/main/resources/lang'...
remote: Counting objects: 2652, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 2652 (delta 2), reused 2 (delta 0), pack-reused 2646
Receiving objects: 100% (2652/2652), 1.21 MiB | 306.00 KiB/s, done.
Resolving deltas: 100% (1987/1987), done.
Checking connectivity... done.
Submodule path 'FredBoat/src/main/resources/lang': checked out '853c95afc72d0a20f70b59bd9322bacfe28eb3f3'`

I definetely downloaded language submodule, but it dosen't work!

**Comment by napstr** [comment]
Found the issue and fixed it in ff31aa31a1680709910372b2f9c939918adc14cc (development branch).
Instead of deleting an old unused string, I accidently uncommented it during a recent refactoring.
"Behaviour is unchanged:tm:" memes are temporarily allowed in here :P

**Comment by KKHaneul** [comment]
@napstr Thank you! 😄
