### ISSUE TITLE
Blacklist command

### ISSUE THREAD

**Issue by L4by** [Frederikam/FredBoat#309]
BOT_OWNER can unblacklist user to ;;unblacklist command, but cannot add to blacklist user. so i suggest blacklist command.

Usage: ;;blacklist <add/del/list> (same ;;admin, ;;dj, ;;user)
Blacklist add, del: ;;blacklist <add/del> <user/role>

If someone's added blacklist, cannot use bot's all features/commands.

※ Sorry for my bad english =(

**Comment by napstr** [comment]
Thanks, this has been on our [roadmap](https://github.com/Frederikam/FredBoat/projects/2) informally, linked this issue instead.

**Comment by KKHaneul** [comment]
Thanks!

**Comment by KKHaneul** [comment]
More suggest blacklist features:

Only BOT_OWNER can modify blacklists. and can add discord server to input servers id.

**Comment by napstr** [comment]
This is being worked on in #330
