### ISSUE TITLE
Create ;;playNext command

### ISSUE THREAD

**Issue by jbelford** [Frederikam/FredBoat#31]
;;playNext or ;;playn. Whatever works.

A command that places a song (maybe even playlist?) at the head of the queue. Useful when there is a large playlist taking up space in the queue and just want to add song without clearing it.

**Comment by Frederikam** [comment]
Why the close? This is actually not a bad idea.

**Comment by napstr** [comment]
![image](https://cloud.githubusercontent.com/assets/6048348/24212015/332dd918-0f2e-11e7-9bc0-eb7cd031f1bc.png)
