### ISSUE TITLE
Create a history command

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#314]
Create a history command. This would be similar to ;;list, but instead of showing queued tracks it would be showing ended tracks.

**Comment by mohanarpit** [comment]
Hey @Frederikam, is it OK if I can pick this up?

**Comment by Frederikam** [comment]
That'd be great. Normally I would give some advice on how to do this, but I'm rather busy today. Good luck!

**Comment by mohanarpit** [comment]
Thanks for your quick response. Do let me know your thoughts whenever you have the time. In the meantime, I'm poking around with the bot to check out and understand the code flow.

**Comment by Frederikam** [comment]
I'd start by taking a look at the `ListCommand` and the `GuildPlayer` classes

**Comment by mohanarpit** [comment]
Thanks! Will do.

**Comment by napstr** [comment]
You probably want to have a fixed size (how long do we want the history to be?) queue in the GuildPlayer where you drop in tracks that finish playing.

**Comment by sbcd90** [comment]
Hello @Frederikam , @napstr , 
I provided a PR for this issue. Can this PR be reviewed?

**Comment by mohanarpit** [comment]
@sbcd90 Would have appreciated a heads up that you were working on this. I had already made changes on my local for this issue. Anyway, I'm going to back off on this issue and stash my changes. 
Thanks @Frederikam & @napstr, it was a good learning experience working on this project.

**Comment by Frederikam** [comment]
It's unfortunate that we can't merge both PRs. @mohanarpit thanks for your effort anyways though
