### ISSUE TITLE
Self hosted FredBoat doesnt respond

### ISSUE THREAD

**Issue by sbcd90** [Frederikam/FredBoat#316]
Hello,

I'm trying to self host FredBoat using the master branch & the self-hosted fredboat doesn't respond.
I have attached the config.yaml & credentials.yaml as well as the log files for detail.
Unfortunately, I dont see any error in the logs.
Can someone please help?

[target.zip](https://github.com/Frederikam/FredBoat/files/1345422/target.zip)

I'm trying to run commands like 

```
;;play https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

**Comment by RealKC** [comment]
Please do NOT post your token online, reset it right now!

**Comment by napstr** [comment]
This it not an issue with code and does not belong here. Feel free to join #selfhosters in [FredBoat Hangout](https://discord.gg/cgPFW4q) and share your logs via https://hastebin.com/ or a similar paste service.
