### ISSUE TITLE
Hacktoberfest 2017 - How to contribute

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#322]
![image](https://user-images.githubusercontent.com/2582617/31047306-6f33497c-a608-11e7-8e77-7b4cf33f2b0f.png)

[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is upon us and I wanted to share some information to anyone who might come across FredBoat because of it. 

## What is FredBoat?
* FredBoat is mainly a Discord music bot
* It is available in over 400,000 Discord servers
* Many people selfhost FredBoat for a small handful of servers
* Also see https://fredboat.com/

## How do I do XYZ?
* Read our [developer documentation](https://github.com/Frederikam/FredBoat/blob/master/CONTRIBUTING.md)
* Read our [user documentation](https://fredboat.com/docs)
* If you can't find what you are looking for, be sure to ask. You can reply here or create a new issue.
* You can ask in our [Discord server's](https://discord.gg/cgPFW4q) #coding channel

## How can I contribute?
* See which issues are labelled [Hacktoberfest](https://github.com/Frederikam/FredBoat/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest)
* Create a new issue (even if you don't intend to work on it, others might want to pick it up!)

## Rules
* If we request changes and you don't reply within a reasonable amount of time, we will mark your PR as invalid until you respond.
* Please reply to an issue if you decide to take it up so others don't claim it
* Please don't claim an issue someone else began working on. This isn't a race and we can't merge two PRs of the same feature!

**Comment by napstr** [comment]
Thanks for being awesome and making FredBoat better! I hope you reached your goal for getting the Hacktoberfest shirt. You can check out your progress under https://hacktoberfest.digitalocean.com/

@knight-ryu12
@bobatrance 
@Nanabell 
@BadJukeBox
@TernundaHunter 
@SuhanKoh
@kantenkugel 
@yeoji
@sbcd90
@RealKC
