### ISSUE TITLE
[Discussion] Should commands implement a boolean to be disabled ?

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#324]
As the title suggests should commands implement a bool so we can easily disable them at runtime without the need of eval and possibly reflection. If any command would be broken or needed maintenance in some way we could disable the command until we found/deployed a fix

**Comment by Frederikam** [comment]
As I said in the staff chat, I think this is a good idea

**Comment by napstr** [comment]
This is being worked on in #326.
