### ISSUE TITLE
Bot isn't starting

### ISSUE THREAD

**Issue by InterXellar** [Frederikam/FredBoat#328]
So followed the Manual for Selfhosting and did everything as it should be, but still the bot refuses to start.
Here the log on pastebin
https://pastebin.com/0RgxZ89D

I hope someone can help me.

**Comment by napstr** [comment]
I can't reproduce it. The 909 build jar runs fine for me on my system, both with and without a jdbc url.
What JVM are you using? Please share the output of `java -version`.

**Comment by InterXellar** [comment]
Here's the output. I always use OpenJDK and i never had a Problem with it:

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by napstr** [comment]
No luck, using OpenJDK works fine for me too. Do you have the same issue with the stable build?

**Comment by InterXellar** [comment]
The Stable Build works without Problems.

**Comment by InterXellar** [comment]
I found the Error. I redownloaded the Bleeding Edge Build and it just worked fine. I'm sorry that i wasted your Time.

**Comment by napstr** [comment]
This error popped up a few days ago in our Discord for a different user.
Googling around [leads to hints](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/43574427) that this might be related to java 9, but you aren't using java 9 and it is inconsistent between builds :thinking:

**Comment by napstr** [comment]
Oh rip
> I found the Error.

Please share for future reference.
