### ISSUE TITLE
Command to change bot avatar

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#333]
This would be a simple command that takes an image file and sets it as the bot's avatar.

Possible usage:
![image](https://user-images.githubusercontent.com/2582617/31069392-95b2999a-a75c-11e7-87c5-8c382bcbe71d.png)

This command would be restricted with the `BOT_ADMIN` permission.

**Comment by napstr** [comment]
Better to use `;;setavatar` since there's already an `;;avatar` command

**Comment by Frederikam** [comment]
Ah, my bad

**Comment by yeoji** [comment]
I gave this a go and have opened a pull request :)

**Comment by napstr** [comment]
#338 resolves this.

**Comment by ashleykrose** [comment]
This no longer works. Was it removed?

**Comment by napstr** [comment]
It was never removed.
![image](https://user-images.githubusercontent.com/6048348/43034476-6e701012-8cdd-11e8-93b8-24920b316035.png)

**Comment by ashleykrose** [comment]
![capture](https://user-images.githubusercontent.com/8593303/43111017-16ef15fe-8ebd-11e8-900f-d25279296157.JPG)

**Comment by ashleykrose** [comment]
it didn't set it for me

**Comment by Frederikam** [comment]
1) There are no FredBoat with write access to that channel, as it would respond
2) You need to be a bot admin, which you certainly aren't of the main FredBoat

**Comment by ashleykrose** [comment]
how to i do that?

**Comment by ashleykrose** [comment]
![capture](https://user-images.githubusercontent.com/8593303/43111523-ad52a68a-8ebf-11e8-9d90-eeb79477e3de.JPG)

**Comment by Frederikam** [comment]
Host your own bot if you want to change the avatar
