### ISSUE TITLE
Some commands could use embeds once we get on JDA 3.x

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#34]
AFAIK JDA supports them only in 3.x, so we'll have to wait for the music stuff to be implemented which should be this month.

These are the commands I suggest to use embeds: ;;akinator, ;;list, ;;play <name of video>, and maybe some I couldn't think of.

**Comment by Frederikam** [comment]
I have been wanting to get into using embeds, but I'm currently waiting on
JDA 3.0. Mock-ups are welcome, though.

**Comment by RealKC** [comment]
List of commands that should use embeds: 
;;akinator, 
;;nowplaying,
;;play(when used to search for a song), 
;;music, 
;;list, 
;;roll, ;;pat, ;;hug, if possible.

These are the ones I can think of ATM, the music commands in this list should use blue for the sidebar color thingy if executed by the normal bot, or the normal music not, or orange if executed by the patreon bot.

**Comment by Frederikam** [comment]
I'm currently working on `;;nowplaying`, but how would you expect these to look?

**Comment by RealKC** [comment]
For one they should show at the very top who issued the command, they avatar and their discrim, ;;play, ;;nowplaying, and ;;list should use markdown formatting to link the videos, but other than that, you can do whatever you want, and I'll suggest changes based on what you did.

**Comment by Frederikam** [comment]
For reference:
![image](https://cloud.githubusercontent.com/assets/2582617/21074706/dd0e502c-beff-11e6-8a55-4f961cb4b404.png)

**Comment by RealKC** [comment]
That looks good

**Comment by Frederikam** [comment]
The only command I can think of that could benefit from an embed is when using `;;play` to search

**Comment by Nanabell** [comment]
the ;;list Command as Embed might be nice aswell if you store the link to the yt video for example you can lust link to them via markdown.
idk about the ;;music command it might be to long to fit it nicly into an embed

**Comment by RealKC** [comment]
Yeah, ;;music has become quite big, I don't think it'd look nice in an embed, unless we use pages, I guess, but idk about that.

**Comment by Frederikam** [comment]
We could also just link to a webpage written in markdown

**Comment by RealKC** [comment]
That could work too, `docs.fredboat.com/music`?

**Comment by Frederikam** [comment]
Sure

**Comment by RealKC** [comment]
>the ;;list Command as Embed might be nice aswell if you store the link to the yt video for example you can lust link to them via markdown.
Adding more to this, you could have pages and have each page show 10 songs

**Comment by Frederikam** [comment]
> Adding more to this, you could have pages and have each page show 10 songs

That is something I plan to do, just haven't written it down. I should probably do both at once.

**Comment by RealKC** [comment]
Closing this as the issue is unnecessary at this point.
