### ISSUE TITLE
Incorrect help text for GetNodeCommand

### ISSUE THREAD

**Issue by Shredder121** [Frederikam/FredBoat#344]
https://github.com/Frederikam/FredBoat/blob/564dd1997267cdf0de01c2323f3f2a9c3045db1f/FredBoat/src/main/java/fredboat/command/admin/GetNodeCommand.java#L44-L47

**Comment by Shredder121** [comment]
Yup, thanks.
Do we wait for it to be in master to make it auto-close or not?

(P.S we could consider making `development` the 'default' branch, and maybe rename `master` to `stable` or something)

**Comment by napstr** [comment]
I've been closing issues as soon as the code is in development. As for the adjustments I would like them. @Frederikam's call though.
