### ISSUE TITLE
Bot didn't play any song and can't destroy, but some other server can(?)

### ISSUE THREAD

**Issue by KuroiKaizoku** [Frederikam/FredBoat#345]
<img width="529" alt="fred1" src="https://user-images.githubusercontent.com/12051679/31164341-ede75e74-a910-11e7-8bcd-8b8591b975d8.PNG">

I guess it started since the last update, it seems to work only in this server and not the other server that i have
we're able to insert a song but we cant hear it, we try to destroy the list but the error pop up
we also tried switch region and it still didn't work

**Comment by Kurozume** [comment]
Even though it is an unlikely scenario, make absolutely sure the bot has the permissions it needs:

To allow FredBoat to connect to a voice channel and play music, you need to click the settings icon for your voice channel and give it the following permissions:
    - View Channel
    - Connect
    - Speak
    - Use Voice Activity
If you don't know how to do this; here is a gif to help out: https://uzume.s-ul.eu/Ad2HQbpQ.gif


_Sent from my Xperia XZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KuroiKaizoku** [comment]
the bot have full permissions (since the owner is too lazy to setup the role), resetting the permission still doesn't solve it as well

**Comment by napstr** [comment]
Hi, thanks for reporting.
Could you give us a bit more details what order of commands led to this state?

**Comment by Nanabell** [comment]
@napstr i belive @Frederikam fixed this in https://github.com/Frederikam/Lavalink/commit/d0df583022293e71dcfc663e5ef3e59198785809

**Comment by KuroiKaizoku** [comment]
we both try play a couple of music list, the bot started as usual but it didn't play anything and yet somehow its running(?)
we both then try to destroy and that error log popped up
that's all i can say

**Comment by KuroiKaizoku** [comment]
apparently kicking and re-invite the bot works
we still don't know what cause the bug tho

**Comment by Frederikam** [comment]
Fixed in https://github.com/Frederikam/Lavalink/commit/d0df583022293e71dcfc663e5ef3e59198785809, which is not live yet. Please have patience

**Comment by knight-ryu12** [comment]
isn't it live in pub bot?

**Comment by knight-ryu12** [comment]
isn't it live in pub bot?

**Comment by Frederikam** [comment]
Yeah it is
