### ISSUE TITLE
Setting the current active text channel

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#348]
We are somewhat inconsistent in setting the currently active text channel of the guild player. Some music commands do it, some don't, I suspect that's an oversight. It _seems_ to lead to a few errors in the logs. What should be the policy here?
My natural suggestion would be to check for it at a central place (CommandManager.java) right before calling Command#onInvoke and just set it from there for every music command
```java
if (invoked instanceof IMusicCommand) {
  PlayerRegistry.getExisting(guild).setActiveTextchannel(channel); //add a nullcheck etc but you get the idea
}
```

**Comment by Nanabell** [comment]
the thing with this system would be every command issued in a diffrent channel would override the current channel. same with admin commands like `revive`, `eval`, `nodes` etc etc

**Comment by napstr** [comment]
That's why I proposed it to be just the Music Commands.
