### ISSUE TITLE
Fix or replace MAL command

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#350]
The MyAnimeList command is somewhat broken due to the MAL API exhibiting some weird quirks. For example, after an unsuccessful search any follow up requests will be answered after a full minute.

The options of fixing this include researching their API specs, maybe find a way to get whitelisted (there appear to be forum discussions on that topic from years ago), or switching to a different anime API. Either way whatever the new solution looks like, it should be including a cache and proper rate limit handling.

**Comment by RealKC** [comment]
We could potentially move to AniList's API. Docs are [here](http://anilist-api.readthedocs.io/en/latest/index.html).

These are some nice notes from taiga.moe's FAQ ![](https://ping-b1nzy.today/b81a60.png)

**Comment by Nanabell** [comment]
aniList's API is massive and so much better documented than mal imo

**Comment by dashwav** [comment]
Correct docs for Anilist would be [here](https://anilist.gitbooks.io/anilist-apiv2-docs/). Their API v1 is getting deprecated in March of 2018. What I have done in a few projects before is use the AniList API to search for the entry, and if it is found use that info to grab the correct link from MAL.

**Comment by Frederikam** [comment]
The mal command is deprecated and we do not seek to replace it. it will be removed in the next major release
