### ISSUE TITLE
Where can I find the .yaml file WITHOUT IT BEING AN .EXAMPLE FILE!

### ISSUE THREAD

**Issue by babdab9** [Frederikam/FredBoat#354]
I wanna make me a new self-hosted bot ya know :) I am not a developer and I am only 13yrs old. 

Contact me thru Discord if easy:@ThatGreekGuy#7780

**Comment by Frederikam** [comment]
![image](https://fred.moe/Krm.gif)

**Comment by babdab9** [comment]
I did it!!! Just, there is a weiird exeption.

**Comment by babdab9** [comment]
Exeption about thread main
