### ISSUE TITLE
Ratelimiter adjustments

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#359]
![image](https://user-images.githubusercontent.com/13600006/31407501-6bea36d6-ae05-11e7-821c-1d84667fb39e.png)
While the current rate limiter is good for spamming skips and similar, I fear it's not quite strict enough for queueing songs as it needs several 10s of songs to be spammed for the rate limiter to kick in.

**Comment by napstr** [comment]
Sounds like a moderation issue. Our internal ratelimiter exists to stop resource intensive abuse (for which it works great given there was no incident related to that so far), not fix user behaviour.

This fits the issue presented in the above screenshot better imo: https://github.com/Frederikam/FredBoat/issues/365

Tentatively closing this as a duplicate. Lemme know if I missed something.
