### ISSUE TITLE
;;adebug not work as intended

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#361]
We are now using LavaLink, so this command might not work/borked.

**Comment by napstr** [comment]
It's still perfectly fine for selfhosters. So probably add a message to use the ;;nodes command if lavalink is enabled?

**Comment by knight-ryu12** [comment]
I gonna work on it.

2017/10/12 午後5:28 "Napster" <notifications@github.com>:

It's still perfectly fine for selfhosters. So probably add a message to use
the ;;nodes command if lavalink is enabled?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Frederikam/FredBoat/issues/361#issuecomment-336058462>,
or mute the thread
