### ISSUE TITLE
Add BountySource to allow incentive for features.

### ISSUE THREAD

**Issue by majorcyto** [Frederikam/FredBoat#371]
Hi,

I have seen this used successfully with other open source projects, [BountySource](https://www.bountysource.com/) allows you to put a cash money "bounty" on features. You can either open them yourselves for people to submit pull requests and collect the bounty. Or on the flip side, allow normal users to add a bounty (that you approve) that they will basically pay once it is implemented and completed.

Multiple users can contribute to 1 bounty, raising its pledge higher for more people that want it as well. It might be a decent way to "fund" work on the Dashboard.

**Comment by Frederikam** [comment]
I don't believe this to be the correct way of funding the dashboard. This site only looks useful for well-defined issues, unlike the idea of a dashboard which isn't completely thought out yet.

What other use-cases can you think of? Would you consider pledging yourself?

**Comment by majorcyto** [comment]
While it can be used for show-stopper issues as well. (I have seen it used for instance in WoW Emulation Projects like [TrinityCore](https://www.bountysource.com/teams/trinitycore/issues?tracker_ids=1310)).

But it is also something that can be used for feature requests that maybe you would not consider generally (because it is a time consuming task) but turns out multiple people want, and will pay for. For instance, this is more akin to lava-player but pledging for regional-node support is something I would do.

For FredBoat specifically I could see people pledging for things that are still inline with your suggestion list but they want it sooner, like custom prefix support, custom nickname support, maybe api integration (such as ani-api, instead of mal), New embeds, new config options, new sources (all though this is really through lavaplayer).

I have seen BountySource issues go as high as $300+ on the TrinityCore one just to get it to be worked on sooner. Never underestimate how much people want something trivial lol. You can still reject new BountySource issues that will never be in-line with your goals just by closing the issue (such as XP/Level system).

**Comment by Frederikam** [comment]
I'm not convinced there is enough engagement from the community to justify this. I invite you to prove me wrong.

**Comment by majorcyto** [comment]
You are the owner, if you do not feel it is worth your time then I understand and will not fight further about it. I just thought it would be an easy way for users who want to, to basically "pay" their way into a feature. And for your team to make extra dev/server bill money on the side.

I will close this.

**Comment by Frederikam** [comment]
I mean, I'm open to the idea. Though if only a couple people are interested I don't think it would be a success.

**Comment by Macley-Kun** [comment]
Can't we ask the public if their are interested? Making a poll and announce it on the server/twitter?
