### ISSUE TITLE
AnnounceCommand.java?

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#373]
[/src/main/java/fredboat/command/admin/AnnounceCommand.java](https://github.com/Frederikam/FredBoat/blob/development/FredBoat/src/main/java/fredboat/command/admin/AnnounceCommand.java)

How can i use it? i tried announce command but doesn't work.

![2017-10-22_083740](https://user-images.githubusercontent.com/27128153/31856762-52da9eda-b704-11e7-87f7-24f8f101171a.png)

**Comment by Frederikam** [comment]
The command requires an argument

**Comment by napstr** [comment]
79fefd4b7e1c674271d0dd2aa0584a1036f155d9 should prevent this.
