### ISSUE TITLE
Leave Server command

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#378]
This thread is for suggest.

Only Bot owner can use this command.
At send ;;leaveserver command in server what bot is entered, bot can leave server self.

**Comment by babdab9** [comment]
Excuse me, but because English is not my native toungue, can I have a better explanation :D

**Comment by RealKC** [comment]
@babdab9 OP is asking for a command that makes FredBoat leave the server the command is excuted in.
