### ISSUE TITLE
Clarify branch names

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#387]
This came up more than once in internal discussions, so I'm opening an issue so that we can reach a decision.

Proposed changes:
- Rename master branch to `stable`, keep it protected as it is currently
- Make development branch the main branch of the repo so that github integrations (like closing issues once a PR is merged) work properly

@Shredder121 @Nanabell @Frederikam please check if I missed something and/or voice your opinion.

**Comment by Nanabell** [comment]
so we are keeping the name "development" for the config option?
Not saying I'm not fine with it just asking to clarify since its still the same name as the branch even if we rename master

**Comment by napstr** [comment]
I expect FredBoat to move to a state where there is no reason for selfhosters to be using that option.

**Comment by Frederikam** [comment]
What do we call the development branch then? Does it need to be called "master"? Can we rename it to "dev" for consistency with Lavalink?

**Comment by napstr** [comment]
Can we get this done please? I'd like to tag the docker releases by branch names and write according documentation and docker-compose files.
stable and dev are fine by me.

**Comment by Frederikam** [comment]
Created branches `stable` and `dev`
