### ISSUE TITLE
Selfhosting docs lead to wrong "stable" build

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#394]
with the recent changes to the old branches "Master" and "development" to be "stable" and "dev" whereby stable is protected and dev is default branch. the self-hosting docs for the stable download leads to the `<default>` branch, which is the dev now

edit: proposal as new link
https://ci.fredboat.com/viewLog.html?buildTypeId=FredBoat_Build&buildId=lastSuccessful&buildBranch=refs%2Fheads%2Fstable&tab=artifacts&guest=1

**Comment by napstr** [comment]
:+1: 

https://github.com/FredBoat/fredboat.com/commit/059f5332ec2c92977c8b5b28d37dcfb3fd8d30ef
