### ISSUE TITLE
Bot clearing queue

### ISSUE THREAD

**Issue by Misat11** [Frederikam/FredBoat#396]
Hi,
I have just started using your bot (not selfhosting) and I really liked it.
I have a playlist with 183 songs.
I added it to bot, activated repeat mode and made it shuffle.
I leaved my music room and I came back  after few hours. (The few hours is in next day :smiley: )
Queue stilll had some songs, after I typed _;;queue_, but bot is not in room.
I typed _;;join_ and queue is cleared.

Thank you for any answer and wish a nice day :smiley:

**Comment by napstr** [comment]
There was complete restart yesterday which is the likely cause for this.

Please join our Discord server (https://discord.gg/cgPFW4q) and drop questions like this in our #support channel instead of the github issue tracker.
