### ISSUE TITLE
Thread stuck in split select detection regex

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#399]
We recently encountered an unresponsive shard with its main thread stuck in a regex. Here's the relevant part of the threaddump:
https://hastebin.com/voqugexodu.txt

**Comment by napstr** [comment]
One thing that would make hunting the source of this down easier is logging threads by adding `[%thread]` to the logback patterns.

**Comment by Shredder121** [comment]
I do see the regex is problematic and has a catastrophic backtracking problem.
I'll rewrite it.
