### ISSUE TITLE
Default playlist

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#40]
>[2:43 PM] Nakonssika (Настя): I suggest to add possibility to create default playlist and edit it for Bot to play. 
Thank you for considering it :smiley:
[3:12 PM] Nakonssika (Настя): I suppose, that it should work like:
>1) A global default playlist
>2) A possibility to edit it, adding or deleting songs or even overriding it to create a specific playlist for each server. 
>3) An option for each server, like a switch mode, in which you can set on or off this playlist
>
>[4:20 PM] Fred's Robot Pet: just need the info when the default song should play
[4:20 PM] Nakonssika (Настя): automatically, when the bot is launched.
[4:21 PM] Nakonssika (Настя): summoned, i think
[4:21 PM] Nakonssika (Настя): and admin can control this, using the on\pff function
[4:21 PM] Nakonssika (Настя): las a setting
[4:21 PM] Nakonssika (Настя): like*
[4:22 PM] Fred's Robot Pet: i think it should play when people join in a voice channel and also say "The default playlist is now playing"
[4:22 PM] Nakonssika (Настя): yes, like this. and if you use (play) and some song, then the default playlist is skipped.
[4:23 PM] Nakonssika (Настя): but still exists

I'll also add some things to this:
1) ;;default global/server should post a link to the list of all songs in the default playlist on hastebin;
2) ;;default skip should skip it;
3) ;;default play should play it.

This feature could have integration with the dashboard as well.

**Comment by Frederikam** [comment]
I think this is a bad idea. You can't create a playlist any person would enjoy listening to. If I start the player, I expect there to be no playing tracks before I actually add some.

**Comment by napstr** [comment]
Could this be a thing if we allowed users to set this on a per server basis?

Imagine a command like this:
`;;defaultplaylist <optional playlist link>`

Called without a parameter it would save the current playlist as the default playlist, called with a playlist link whatever is found in that link.

**Comment by Frederikam** [comment]
@napstr what would happen once a server has associated a default playlist?

**Comment by Nanabell** [comment]
it would say something like "You can set a default playlist via ;;defaultplaylist ...
i'd guess

**Comment by napstr** [comment]
Once associated, I'd expect the following behavior:

In case of an empty playlist in the player and user present in a voice channel with Fredboat, FredBoat would start playing songs (randomly, or keeping track of the last played song or something) off that default playlist. When a user adds a song, it will play his song(s) next, after finishing the current song which came from the default playlist (if the user wishes to have his song played at once he can just skip the default playlist song).

I can see how this could increase the load on FredBoat with users afking in channels. Judging whether that impact will be a problem is up to you Fred.
