### ISSUE TITLE
Rejoin channels on shard reconnect

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#403]
I'm not entirely sure what actually happens when a shard has to do a reconnect (and resume too), what it should do is reconnect to the channels it was playing in, similar to the mechanism we have in place for reviving shards.
We can probably use JDA's onDisconnect/onResume/onReconnect events for this.

One thing to note is that if we do rejoin a channel, to check whether it was emptied in the meantime, and pause ourselves in that case.

If this happens already automatically this issue can be closed upon confirmation.

**Comment by napstr** [comment]
Metrics graphs and event logs suggest that we loose audio connections during resumes, so this is definitely a relevant issue.

**Comment by napstr** [comment]
Tested this with latest LL and FB code, resumes are not handled optimally.
They bot always leaves the voicechat, music is paused, unpaused on rejoin.
Sometimes it does not rejoin, and therefore does not continue the playback.

Reconnects break it worse: Never rejoins the voicechat, but always keeps playing.

**Comment by Frederikam** [comment]
Can you reopen as a Lavalink issue then?
