### ISSUE TITLE
Send greeting and primer on guild join

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#406]
When joining a guild, send a greeting and small primer on what FredBoat can do + relevant links to the public channel / first channel we can write in.

~~@TernundaHunter prepared a text:~~
> ~~Thanks for using Fredboat Music! To get started, join a voice channel and type ;;play <song name>. I'll give you a list of 5 songs where you can choose one by typing ;;play <number of the song you want>.~~
> 
> ~~Type ;;commands for a list of commands you can use! Or go to <https://fredboat.com/docs> for a full review of what I can do. Type ;;help for documents, bot invite links, and an invite to the Fredboat Hangout Discord Server.~~
> 
> ~~You can set the bot to announce music as it plays and automatically resume when a user enters the channel with the ;;config command.~~
> 
> ~~I can speak your language, too! Type ;;lang to see a list of languages I can speak. It should look like this: ``;;lang en_US`` but with your language code.~~
> 
> ~~I have a built in permissions system you can use! Follow this link to learn more: <https://fredboat.com/docs/permissions>~~

See post below for proper formatting.

**Comment by TernundaHunter** [comment]
The formatting farted when posted. 

Thanks for using Fredboat Music! To get started, join a voice channel and type ``;;play <song name>``. I'll give you a list of 5 songs where you can choose one by typing ``;;play <number>``. 

Type ``;;commands`` for a list of commands you can use! Or go to <https://fredboat.com/docs> for a full review of what I can do. Type ;;help for documents, bot invite links, and an invite to the Fredboat Hangout Discord Server.

You can set the bot to announce music as it plays and automatically resume when a user enters the channel with the ``;;config`` command.

I can speak your language, too! Type ;;lang to see a list of languages I can speak. It should look like this: ``;;lang en_US`` but with your language code.

I have a built in permissions system you can use! Follow this link to learn more: <https://fredboat.com/docs/permissions>

**Comment by knight-ryu12** [comment]
Should I put this hardcoded? or i18n

**Comment by napstr** [comment]
I think we can skip the translations on this one, since it would be posted on guild join, where a language has not been set. We can always add translations if we find that should be used in another / a different way.

**Comment by knight-ryu12** [comment]
Should we look up DB to not send "twice"? (Like Kick-Reinvite)

**Comment by napstr** [comment]
I don't think that would be a problem.

**Comment by Frederikam** [comment]
I think that would be annoying and I would avoid it

**Comment by babdab9** [comment]
Avoid sending wice or sending it **at all**?

**Comment by Frederikam** [comment]
More than once

**Comment by babdab9** [comment]
yea but that would require a uid for each server.. .oh who am I kiddin there is the guild id

**Comment by napstr** [comment]
Suggestion: Avoid sending it twice, but add a command like `;;hello` so users can resend it.

@knight-ryu12 are you working on this? I'd like to pick this one up.

**Comment by knight-ryu12** [comment]
Go ahead and take this. @Napster

2018/01/22 午後5:55 "Napster" <notifications@github.com>:

**Comment by napstr** [comment]
#439

**Comment by napstr** [comment]
Wrong one lol

**Comment by knight-ryu12** [comment]
lol

**Comment by napstr** [comment]
e32ddd38d3787cc345aa6660b1d4744cacdec34a
