### ISSUE TITLE
Remove references to decommissioned FredBoat

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#407]
The decommissioned FredBoat (the one without the musical notes in the name) shows up in several places in the code / documentation still.
Places to check: 
- The help message users receive when saying `;;help`
- The website  (see repo here https://github.com/FredBoat/fredboat.com)
- Maybe others?

**Comment by babdab9** [comment]
Isn't this a string file problem

**Comment by Frederikam** [comment]
Yes

**Comment by babdab9** [comment]
I am getting this, if you don't mind

**Comment by babdab9** [comment]
Website PR should be up soon:tm: Sorry for the waiting but real life sometimes...

**Comment by babdab9** [comment]
aaaaaaaaaaaaand done

**Comment by babdab9** [comment]
🤔 this is still not colsed. Have I done smth wrong?

**Comment by napstr** [comment]
There are some code references still there but those will probably disappear as part of #395 or the aftermath of it. I'm not aware of any place facing users that reference the old boat so I'll consider this issue done.

**Comment by babdab9** [comment]
👍
