### ISSUE TITLE
Self Hosted Bot Won't Launch

### ISSUE THREAD

**Issue by daveb778** [Frederikam/FredBoat#416]
I tried using the bot a while ago and it kept spitting out audio errors so i went ahead and restarted it. Now it wont log in anymore it spits out errors about sql. I have tried updating to the latest jar, i haven't changed anything in the config files, i have double checked my keys and they are correct. I had also copied everything over to my windows desktop with no luck.
[FredBoat.log](https://github.com/Frederikam/FredBoat/files/1545330/FredBoat.log)

**Comment by napstr** [comment]
You are missing a postgres database. Read the selfhosting guide for more details: https://fredboat.com/docs/selfhosting
