### ISSUE TITLE
could we get support for norwegian radio (p4-p5)

### ISSUE THREAD

**Issue by the-sloth** [Frederikam/FredBoat#417]
every channel is under http://stream.p4.no/*
original link(norwegian): https://www.p4.no/lyttesenter/

Channel P4: (everything here is same channel with different format or quality)
mp3 (medium quality): http://stream.p4.no/p4_mp3_mq
mp3 (high quality): http://stream.p4.no/p4_mp3_hq
aac (medium quality): http://stream.p4.no/p4_aac_mq
aac (low quality): http://stream.p4.no/p4_aac_lq

Channel P5:
mp3 (medium quality): http://stream.p4.no/p5oslo_mp3_mq
mp3 (high quality): http://stream.p4.no/p5oslo_mp3_hq
aac (medium quality): http://stream.p4.no/p5oslo_aac_mq
aac (low quality): http://stream.p4.no/p5oslo_aac_lq

**Comment by knight-ryu12** [comment]
well, if you're reffering to public bot, answer is likely No.
If you're refering to selfhosted bot, this should be working.

**Comment by napstr** [comment]
This looks related to #321
