### ISSUE TITLE
Idle music

### ISSUE THREAD

**Issue by AutisticScrub** [Frederikam/FredBoat#418]
could you add a command that will play a playlist or song that the bot manager chooses when the bot is idle/the queue is empty?

**Comment by MrJacz** [comment]
Just find a playlist and leave it on repeat?

**Comment by MrJacz** [comment]
@AutisticScrub On the roadmap its a planned feature :)

**Comment by napstr** [comment]
Duplicate of #277

**Comment by napstr** [comment]
@MrJacz where do you see this on the roadmap?

**Comment by MrJacz** [comment]
![image](https://user-images.githubusercontent.com/23615291/33929248-edaef3be-e03c-11e7-985d-abfab5cbf7de.png)
it wasn't the roadmap actually it was the player but still related to upcoming features, no?
