### ISSUE TITLE
when we use np command we get the following error at random (self hosted, have not changed anything)

### ISSUE THREAD

**Issue by the-sloth** [Frederikam/FredBoat#419]
org.json.JSONException: JSONObject["items"] not found.
    org.json.JSONObject.get(JSONObject.java:520)
    org.json.JSONObject.getJSONArray(JSONObject.java:714)
    fredboat.util.rest.YoutubeAPI.getVideoFromID(YoutubeAPI.java:90)
    fredboat.command.music.info.NowplayingCommand.getYoutubeEmbed(NowplayingCommand.java:100)
    fredboat.command.music.info.NowplayingCommand.onInvoke(NowplayingCommand.java:73)
    fredboat.commandmeta.CommandManager.prefixCalled(CommandManager.java:130)
    ...

**Comment by napstr** [comment]
You are missing the Youtube API key, or its wrong, or the Youtube API is not enabled for that key.
