### ISSUE TITLE
A third repeat mode that moves tracks to the tail instead of restarting

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#42]
If I were to implement this, each player would have one of 3 repeat modes:

1. Ended tracks are deleted (off)
2. Ended tracks are restarted immediately (current ;;repeat)
3. Ended tracks are shuffled back into the queue or put at the the tail, depending on shuffle mode (proposed idea)

I'd like some input on this idea on how the user would switch between the 3 modes. Currently we just toggle between 1 and 2 with `;;repeat`

**Comment by knight-ryu12** [comment]
I'd say, need to make ;;repeat argumented.

**Comment by Frederikam** [comment]
Yeah, that's what I'm thinking, but what would the usage be like? What do we call modes 2 and 3?

**Comment by knight-ryu12** [comment]
that'd be better.
Just 2,3 toggling is ok

**Comment by knight-ryu12** [comment]
can you tell us how queue is handled?

**Comment by Frederikam** [comment]
I could but my classes have just started again. I'll get back to you when I
have the time.

**Comment by Frederikam** [comment]
## How the audio queue works
The queue in FredBoat is partially held in the `GuildPlayer` and the `SimpleTrackProvider`. When an `AudioTrack` is queued, commonly by the `AudioLoader`, the track is added to the provider's internal `ConcurrentLinkedQueue`. This queue is completely independent of shuffle. The shuffled list is sorted when it is requested and cached until the provider is modified.

The SimpleTrackProvider's purpose is to provide audio tracks upon request by the `GuildPlayer`, which keeps the currently playing (or paused) `AudioTrack` for itself. If the end of a track is reached (eg not stopped/skipped) and the player is in the current repeat mode, the track is simply restarted.

**Comment by Frederikam** [comment]
What I'm thinking is this:
```
;;repeat off // Disables repeat
;;repeat single // Repeats a single track until skipped
;;repeat all // Ended tracks are moved back into the queue
;;repeat // Displays usage information
```

**Comment by napstr** [comment]
Why not both?

I understand the two modes not as exclusive.
`repeat all` boils down to never kicking a song out of the queue, instead putting it back in after it has finished playing.
That's not exclusive to having the first song in front of the queue playing over and over again.

imo solve this by just adding a `;;repeatall` command that will cause finished tracks to get added to the back of the queue.

Let me know if my proposal makes sense or you prefer the three-mode thing, so I can implement the preferred solution.

**Comment by knight-ryu12** [comment]
Hmm.
I'd like to prefer theree-mode

**Comment by Frederikam** [comment]
@napstr I don't think that is a very intuitive approach. It can be hard for the user to expect what modes are currently active when we don't have some sort of GUI. Why would the user even think there are two settings of repeating to begin with without reading the docs? Moreover, consider why Spotify allows you to switch between these 3 modes with a single button.

**Comment by napstr** [comment]
Indeed, my proposal isn't great for user experience.

What is the expected behavior of the `skip` command in `repeat all` mode? Should the track be kept in the queue or discarded?

**Comment by Frederikam** [comment]
If repeat all is enabled, the track would be moved to the tail of the queue.

**Comment by Nanabell** [comment]
This can be closed. #93 was merged

**Comment by Frederikam** [comment]
True, thanks for reminding me
