### ISSUE TITLE
;;prefix should have special status to always work, even if the guild-specific prefix was changed

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#423]
;;prefix should always be able to be called with the default prefix like with ;;help
![image](https://user-images.githubusercontent.com/2582617/34321847-102881fc-e818-11e7-9cae-3cdd5ba2ec70.png)
Consider it done

**Comment by knight-ryu12** [comment]
Should be piece of cake if we modify .parse() or EventListenrr

**Comment by Nanabell** [comment]
looking back at it i dunno if this should've been done. The problem i see it when we update the patron bot and someone uses ;;prefix with both bots in the guild

**Comment by Frederikam** [comment]
Alternatively, we could make it just print the prefix, and hint that the user can just use mentions as a prefix to change the prefix of just one bot
