### ISSUE TITLE
.m3u and .pls web scraper

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#43]
FredBoat currently supports live internet radios, but not that many people are using it. It seems that many are not aware how to connect FredBoat to a radio. Current usage is like this:

```
;;play https://gensokyoradio.net/GensokyoRadio.pls
;;play https://gensokyoradio.net/GensokyoRadio.m3u
;;play http://listen.moe/stream.m3u
[etc]
```

Lavaplayer needs a direct link to the playlist file and will fail to load such URLs like `https://gensokyoradio.net` since it returns an HTML page.

I propose the idea that we regex any failed URL identifier for m3u and pls links after lavaplayer has failed to load the identifier as a URL in the `AudioLoader`. The following regex could be used:
```js
/href=\"([\w\d\.\/]{1,}?\.(?:m3u|pls))\"/g
```

**Comment by kantenkugel** [comment]
Would you mind me giving this a try? should i use the site `https://gensokyoradio.net` as an example?

**Comment by Frederikam** [comment]
Yes, and any other sites with m3u/pls links you can think of

**Comment by kantenkugel** [comment]
that example url uses mp3 btw (if i found the correct link in html)

**Comment by Frederikam** [comment]
That's what the pls/m3u files refer to. You just need to provide Lavaplayer with the pls/m3u file and it should take care finding the mp3 link
