### ISSUE TITLE
Kill the DB?

### ISSUE THREAD

**Issue by babdab9** [Frederikam/FredBoat#430]
Well, Docker doesnt want to install on my laptop. And PostgreSQL crashed my computer. So, I ask, what now? No FredBoat, would be an answer. But what if, we used file cache?

Ik that DB system has changed, but it still crashes me!

-Player Hwan

**Comment by napstr** [comment]
This is an open source project, so feel free to implement and maintain an alternative to PostgreSQL.

**Comment by Frederikam** [comment]
Why would you install FredBoat on your laptop? If you insist, you can install FredBoat outside of docker. I use free instances from https://www.elephantsql.com/ for development DBs

**Comment by Macley-Kun** [comment]
Doesn't FredBoat require 8 concurrent connections? The free plan only supports up to 5.

**Comment by Frederikam** [comment]
That hasn't been a problem for me, even with IDEA's database tools also
being connected. Are you using the same plan for both main db and cache?

**Comment by Macley-Kun** [comment]
Yeh I use one db for main and cache. I think w/o cache it would use 3 to 4 connections?

I’m kinda thinking to have a backup database if I wanna move away from Heroku.

Thanks for the information Fred! 0/

Verstuurd vanaf mijn iPhone

> Op 4 jan. 2018 om 13:04 heeft Frederik Ar. Mikkelsen <notifications@github.com> het volgende geschreven:
> 
> That hasn't been a problem for me, even with IDEA's database tools also
> being connected. Are you using the same plan for both main db and cache?
>

**Comment by napstr** [comment]
It does not "require" 8 connections, it's just not a supported configuration setting (using as many connections as cores are available, with a minimum of 2). 2 is probably be fine in most cases, and it's easy enough to make a PR if anyone actually needs some kind of upper limit.

**Comment by babdab9** [comment]
@Frederikam becuz im poor and I have no pc - also dfk is that
@napstr me is no coder

Anyone left without a replly

**Comment by napstr** [comment]
I was thinking that we possibly could provide a dumbed down version of FredBoat missing all the db features / using default values for settings, for those edge cases of ppl who can't get things going on their weird machines and don't mind a restricted version.

**Comment by Shredder121** [comment]
I wouldn't mind that, is it feasible to abstract away the persistence to be a no op?

**Comment by napstr** [comment]
Piping all database calls through EntityWriter / EntityReady might do. But we also do some JPQL / native queries so the class names / descriptions would need to be adjusted.

**Comment by Frederikam** [comment]
>I was thinking that we possibly could provide a dumbed down version of FredBoat missing all the db features / using default values for settings, for those edge cases of ppl who can't get things going on their weird machines and don't mind a restricted version.

I don't like this idea. It seems like it only benefits people who are both:
1. Incapable of installing a Docker on their machine
2. Too poor to pay 1 or 2 $ for a tiny VPS (or FredBoat Patron for that matter)
3. Unwilling/incapable of using a free service like https://www.elephantsql.com/

*and*

4. Unwilling to use a music bot that is easier to configure

**Comment by babdab9** [comment]
mmhm fact. But did you ever consider the fact that 13 years old dont have a cc😂 
Anyways, I have left discord, so I won't have trouble

Goodbye P2!🙋
~~Player Hwan~~ Charalampos

**Comment by Macley-Kun** [comment]
> Unwilling/incapable of using a free service like https://www.elephantsql.com/
Is actully a free service, withoud the need of using a cc @babdab9.

**Comment by babdab9** [comment]
ok. wait until I find how its used and we will talk later. Fred,mind locking this?
