### ISSUE TITLE
Language seems have hardcoded prefix

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#432]
Confirmed by looking in crowdin

**Comment by napstr** [comment]
?

**Comment by Frederikam** [comment]
What strings have hardcoded ;; prefix?

**Comment by knight-ryu12** [comment]
So far, playQueueEmpty

**Comment by knight-ryu12** [comment]
possibly other one have hardcoded.

**Comment by napstr** [comment]
https://github.com/Frederikam/FredBoat/blob/dev/FredBoat/src/main/resources/lang/en_US.properties

Got 9 matches for `;;`

**Comment by knight-ryu12** [comment]
Probably we need to fix with

**Comment by napstr** [comment]
There are measures in place to replace them. If it's missing somewhere, add `String.replace(";;", actualPrefix)`.
The actual issues with language strings is all the hardcoded formatting which translators don't understand how to handle.

**Comment by Frederikam** [comment]
>There are measures in place to replace them

That's true. With that in mind, I'm closing this issue as it isn't even certain that there is a problem

**Comment by napstr** [comment]
Eh, `replaceAll` probably....you get the idea :D

**Comment by Frederikam** [comment]
>Eh, `replaceAll` probably....you get the idea :D

Because languages are weird
