### ISSUE TITLE
Brainfuck command not working

### ISSUE THREAD

**Issue by Nythepegasus** [Frederikam/FredBoat#433]
I might just be stupid, but FredBoat doesn't seem to recognize the "brainfuck" command.

**Comment by Nythepegasus** [comment]
Well, a lot of the non music commands don't work either.

**Comment by napstr** [comment]
These are legacy commands used to run on a second bot. We are one deploy/update away from having these live again after merging both FredBoats into one.

Please direct your questions to our discord support channel if you are unable to check issues and PRs for ongoing developments, before opening irrelevant issues.
