### ISSUE TITLE
Lavalink / lavaplayer metrics collector

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#434]
We need proper metrics for package loss and/or frames sent/nulled/deficit.
We can already take random samples through our existing debug commands, but they are is very inconvenient to see the big picture of what's happening.

To solve this: Create a Prometheus Collector that collects all those stats that we can get from our lavalink nodes.

**Comment by Frederikam** [comment]
Also if you add Link states that would be dank. Would be worthwhile to know how many Links are stuck connecting/disconnecting, if any at all.

Wait for LavaLink v2.0 first though

**Comment by Frederikam** [comment]
Napstr do you have time to work on this in anticipation of the soon-ish rollout of Lavalink v2? It would make monitoring problems early on very easy and fast

**Comment by napstr** [comment]
Related: https://github.com/Frederikam/Lavalink/pull/58
Once that collector is available in the lavalink client build we use, add it to our metrics to resolve this issue.
