### ISSUE TITLE
Invite command printing the wrong link.

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#441]
Issue was reported by user Sleepy💤#6625 in the support chat. 
Quote:

The link from ;;invite keeps giving me a unknown error, it gives me this link 
(Broken) https://discordapp.com/oauth2/authorize?&client_id=184405311681986560&scope=bot 
and the website gives me this link (which works) 

(Works) https://discordapp.com/oauth2/authorize?&client_id=184405253028970496&scope=bot%20identify&redirect_uri=https%3A%2F%2Ffredboat.com%2Fcallback%2Fmusic&response_type=code

**Comment by napstr** [comment]
The account of the public FredBoat is old, from a time where, the app id was not the same as the discord id.
Suggestion: If invite is called on
public FredBoat -> send the invite link
PatronBoat -> send a link to the patreon page
anything else -> keep it as it is right now, where it generates a regular permissionless invite for whatever bot account is logged in

**Comment by napstr** [comment]
@knight-ryu12 are you still working on this?

**Comment by knight-ryu12** [comment]
Yes. Therefore I am doing right now. hence I can't get detection to work.
Take over if you like
