### ISSUE TITLE
Event Webhook Embeds show a wrong time

### ISSUE THREAD

**Issue by Gremagol** [Frederikam/FredBoat#443]
I've been checking, if my VPS has the right timezone. Anyways, the webhook embed shows a wrong time, as you can see in the images. I'm selfhosting version 2.0 of FredBoat. It's running on a Ubuntu 16.04 VPS in Germany. Is this a bug or does FredBoat only use a specific timezone?
![fredboat3](https://user-images.githubusercontent.com/24619854/35475106-de0d4a9e-0398-11e8-8a39-8184154801cd.PNG)
![fredboat4](https://user-images.githubusercontent.com/24619854/35475122-241b5f58-0399-11e8-9b62-3925a8da6aed.PNG)
I would love to know whats going on :)

**Comment by Frederikam** [comment]
IIRC Discord embeds use a UTC timestamp. Your client's local timezone is used. Your VPS timezone shouldn't matter

**Comment by Gremagol** [comment]
I see... but eh, Discord has one hour difference. I'm wondering why it's like that.

**Comment by Frederikam** [comment]
@napstr made this so maybe he knows
