### ISSUE TITLE
cutting edge does not load up spotify

### ISSUE THREAD

**Issue by urielrocks5676** [Frederikam/FredBoat#447]
I've tried many a time to load up a Spotify playlist but it only results in an [error](https://imgur.com/a/S6g6Q) when trying to use a playlist [like this one](https://open.spotify.com/user/urielrocks5676/playlist/4d9Avxkv1l4gJ4TODqbkfR?si=csZH3B2ySaOruzS89qr-qA)

**Comment by napstr** [comment]
Probably missing credentials with enabled Spotify audio source? Only @Frederikam can fix this.

**Comment by Frederikam** [comment]
Closing as CE is dead for now
