### ISSUE TITLE
Play command not working

### ISSUE THREAD

**Issue by daveb778** [Frederikam/FredBoat#456]
I updated the bot today and now im getting lavaplayer errors when i try to use the play command. Everything was working before hand, i updated docker ce, docker-compose and java just to be sure but no luck.
[AkCZk5VN.txt](https://github.com/Frederikam/FredBoat/files/1704434/AkCZk5VN.txt)

**Comment by napstr** [comment]
Update it again. This issue has resolved on 2.3

**Comment by daveb778** [comment]
2.3? Im using the latest 1627 build from ci, still no luck.

**Comment by Frederikam** [comment]
What does the bot say when you run the ;;git command?

**Comment by daveb778** [comment]
it doesnt do anything.

**Comment by Frederikam** [comment]
Are you using the right prefix? The ;;git command should show something like this 
![image](https://user-images.githubusercontent.com/2582617/35938457-70024130-0c49-11e8-954e-6e2c1bcef7d2.png)

**Comment by daveb778** [comment]
does it matter if im using the self hosted bot?

**Comment by napstr** [comment]
Hi, I just discovered an issue with our git branches that happened earlier when we were trying to push a fix for the youtube cipher issue asap, leading to corrupted old code ending up in the HEAD commits. Sorry about that and thanks for reporting and letting us know. A fresh, successful build should be server for both dev and stable in the next few minutes on our CI server.

**Comment by daveb778** [comment]
Oh ok thanks. Also one more issue, for some reason soundcloud causes the bot to reboot.

**Comment by Frederikam** [comment]
>does it matter if im using the self hosted bot?

That shouldn't matter as long as your version isn't ancient

>Oh ok thanks. Also one more issue, for some reason soundcloud causes the bot to reboot.

That sounds very odd. What OS are you running on, and can you tell me the exit code?

**Comment by daveb778** [comment]
I'll post some screen grabs in a bit, but im running debian as the host os.

**Comment by daveb778** [comment]
![image](https://user-images.githubusercontent.com/18433196/35939188-60e42676-0c19-11e8-9609-f63dc6ecfcc1.png)
also still no playback with build 1629, some links work and others dont. as for the soundcloud crash this is what i get.
![image](https://user-images.githubusercontent.com/18433196/35939694-eda49ca2-0c1a-11e8-99f5-7da5e71c7637.png)

**Comment by napstr** [comment]
What is the output of ;;stats?

**Comment by daveb778** [comment]
No response.

**Comment by napstr** [comment]
What about ;;mgit, or ;;mstats?

**Comment by daveb778** [comment]
Oh this isnt good, ive been replacing the jar file with latest one from ci. Hows the build date this off??
![image](https://user-images.githubusercontent.com/18433196/35940416-02ac79ba-0c1d-11e8-892e-f3a95846aaa1.png)

**Comment by napstr** [comment]
>i updated docker ce, docker-compose and java j
>replacing the jar file

This information does not fit together. Are you using docker, or are you running the jar?

**Comment by daveb778** [comment]
docker.

**Comment by daveb778** [comment]
well docker compose.

**Comment by daveb778** [comment]
![image](https://user-images.githubusercontent.com/18433196/35940549-903bfbc0-0c1d-11e8-87b6-750abd90d508.png)

**Comment by napstr** [comment]
Start using watchtower, [or update and restart your docker container manually](https://docs.docker.com/compose/reference/).

**Comment by daveb778** [comment]
I'll look into it, tho im still confused as to how its out of date.

**Comment by daveb778** [comment]
I dont see anything about updating here.

**Comment by napstr** [comment]
This is the FredBoat issue tracker, not the place to learn how to use docker. If you cannot use the tools required to selfhost FredBoat, please use the public boat we provide.
You can find all our selfhosting documentation [here](https://fredboat.com/docs/selfhosting), and if you think something can be improved, you can create pull request with your improvements here: https://github.com/FredBoat/fredboat.com
