### ISSUE TITLE
Enable watchtower by default

### ISSUE THREAD

**Issue by daveb778** [Frederikam/FredBoat#457]
After looking in the docker compose file, shouldn't it be that watch tower is un-commented by default?
![image](https://user-images.githubusercontent.com/18433196/35945570-ad212ccc-0c2e-11e8-9cd5-41344a64b7c0.png)

**Comment by napstr** [comment]
Why?

**Comment by daveb778** [comment]
Why not? It'd make it easier for those who just wanna set it and just leave it running without needing to manually update. Plus given how frequent discord and you guys push out updates it'd make sense to keep idiots like me coming here and asking dumb questions lol.

**Comment by daveb778** [comment]
If not that maybe a small section mentioning it on the docs would work too i guess,

**Comment by napstr** [comment]
![sketch-1518044596766](https://user-images.githubusercontent.com/6048348/35946288-7ee32e98-0c63-11e8-9d37-2dd288902e9b.png)
