### ISSUE TITLE
How to run bot with Dockerfile?

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#459]
Hi! i want to run bot without docker image downloading. so i finding a way how to run bot with 'Dockerfile'. How can i run bot with Full-source build file and Dockerfile? (No from scratch)

**Comment by Kurozume** [comment]
Read the website (Selfhost FredBoat from scratch) as this does not require you to actually build the bot, you can download it from the CI server https://fredboat.com/docs/selfhosting
Also issues of this type should be resolved on the support discord server https://discord.gg/JvUdkc
