### ISSUE TITLE
RepositoryNotFoundException?

### ISSUE THREAD

**Issue by KKHaneul** [Frederikam/FredBoat#460]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FredBoat:generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /root/FredBoat/.git/info

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 6s
16 actionable tasks: 13 executed, 3 up-to-date
```

What's problem..?? I tried git clone -> ./gradlew build.

I'm using Ubuntu 16.04.3 LTS x64.

**Comment by napstr** [comment]
Can not reproduce.

**Comment by KKHaneul** [comment]
@napstr 

https://cdn.discordapp.com/attachments/375979674133594118/411332433196351488/gitnotfound.mp4

plz view this video

**Comment by napstr** [comment]
No thx I will not download and open some arbitrary file.

If you are having trouble getting a working build, use our CI servers: https://fredboat.com/docs/selfhosting#ci-server

**Comment by KKHaneul** [comment]
ok.. if this issue is resolved, please close this issue. thank you!
