### ISSUE TITLE
"Handle User Limit in Voice Channels" breaks joining unlimited channels

### ISSUE THREAD

**Issue by majorcyto** [Frederikam/FredBoat#462]
Hi for the "Handle User Limit in Voice Channels" commit, this actually breaks the bot being able to join a channel set as "Unlimited" unless they have Move Members or Admin permissions. If you set a limit, the bot can join again. If you set it back to unlimited, it breaks unless you give it one of the previously mentioned permissions.

**Comment by napstr** [comment]
Thanks for reporting! :ok_hand:
