### ISSUE TITLE
if using Spotify URL containing Japanese track

### ISSUE THREAD

**Issue by beautea** [Frederikam/FredBoat#463]
if read spotify playlist URL containing Japanese track, pitch and playback speed will be glitch or fail to load
(i using google translate)

example, try this https://open.spotify.com/user/pt862to4e0rz67ib2t7bugjab/playlist/7zlCiBOxMbWiSFYqoRkXQ4?si=aVBTGUaCQ_WTq--B2eENew

**Comment by Frederikam** [comment]
Our Spotify integration doesn't play from Spotify. Instead, it attempts to find the tracks on YouTube and SoundCloud. These tracks are supposedly not popular enough to appear in good quality if at all. It has nothing to do with the titles.

**Comment by beautea** [comment]
i see
