### ISSUE TITLE
Make fredboat have more than one hardware server 

### ISSUE THREAD

**Issue by urielrocks5676** [Frederikam/FredBoat#465]
Currently as-is there is only support to have only one server, what I'm thinking is being able to have multiple hardware servers so it can share out load and be able to still run while another server down (service disruption, etc) that way we can avoid having to wait for down time and have comfort for the users

**Comment by knight-ryu12** [comment]
That's what Lavalink doing.

**Comment by napstr** [comment]
I would say that this is an ongoing effort. Like @knight-ryu12 said, Lavalink was one of steps (a very important one). I'm not sure how this is an "issue", as it is not describing a concrete problem or something that we can clearly act upon. A previous, similar, discussion was #208. One of the major problems is the Discord API lib we are using, where the incoming events, the Discord entity cache, and the outgoing rest events are extremely tightly coupled, so a proper effort in this direction will probably include replacing it, however there are no viable, Java based, alternatives at this point.

**Comment by Frederikam** [comment]
For the record, development on Dike has halted because of different priorities.

**Comment by Frederikam** [comment]
Sentinel was released months ago
