### ISSUE TITLE
;;stop command makes stop playing music in the other channel

### ISSUE THREAD

**Issue by taylor224** [Frederikam/FredBoat#47]
Hello,

First thank you for made the FredBoat.

I am using FredBoat with SelfHosting. I installed FredBoat with SelfHosting document. It working well but I found the FredBoat stop playing music when send ;;stop command in the other server.
Actually, It is not stop playing but in Discord PC client, user cannot hear the music from FredBoat.
At left side of Discord PC client, I can see my FredBoat is saying(Green circle ring is activated). But I can hear the music. When I disconnect from the voice channel and reconnect to music channel, I can hear the music from FredBoat or pause and unpause the FredBoat music.
I think It is Discord client bug, But I think some code related with ;;stop command trigger the Discord client bug.
Please review this bug.

I am running FredBoat in Ubuntu 16.04 LTS.
I installed JAVA JDK with this [document](https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04).
Other procedure is stepped by [FredBoat SelfHosting document](http://docs.frederikam.com/selfhosting).
The server is fresh installed with just python and flask development environment.
Server location is US West and Discord Server location is Singapore.

Thank you.

**Comment by Frederikam** [comment]
Are you saying that you ***can't*** hear music from the client? In which case, this might be related to a Discord client bug that I am sometimes affected by at startup. The temporary fix is to restart your Discord client completely:
![image](https://cloud.githubusercontent.com/assets/2582617/21764072/7e394f10-d661-11e6-830d-d8231281b12b.png)

Then make sure the player is not paused with ;;list. You can see if a track is playing if the remaining time of the queue is going down when you invoke ;;list.

Let me know if you are still having issues after trying this.

**Comment by taylor224** [comment]
Yes, as you said, FredBoat is still playing and broadcasting music but users cannot hear. But sometimes some user in same channel can hear music and the other users cannot hear the music from the FredBoat. 
But I don't know why this Discord bug triggered by ;;stop command. As you said, quit and restart the Discord completely resolve this problem but it is just temporary solution. If user send ;;stop command in the other server, this problem is occurred and user cannot hear the music. If this problem happen randomly, It should be fixed by Discord. But It is happened triggered by ;;stop command, We can find the problem in ;;stop command processing code and fix it.
But in public FredBoat server, seems to not happen. So I am also thinking there are problem in my server environment.

Thank you.

**Comment by Frederikam** [comment]
This is really strange. The only thing the ;;stop command does is stop playing and leave the voice channel. I personally also experience this with users as well, not just with my bot.

**Comment by jagrosh** [comment]
This is a Discord bug, where a bot disconnecting from voice on any server you share with it will cause your client to stop receiving audio from it. For example, if you are on 2 servers with the bot and are listening on one of them, if the bot disconnects from voice (on the _other_ server), your client will stop receiving audio from the bot until you disconnect and reconnect to voice. The reason that the audio might not stop for everyone is because they might not share more servers with the bot.

According to some other discussion about this bug, it has already been fixed in some Discord updates that have not been released yet.
