### ISSUE TITLE
Limit prefix length (very low priority)

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#475]
This is not something that is actually important, but would be good to have as a limitation. A person tried to set the prefix to "cat /dev/urandom | head -c1000" which actually worked. That got him a prefix of 1000 random characters as seen in the screenshot. After a brief why-would-anyone-do-this talk with others, it would be reasonable to have the prefix length be between 1-6/1-10 characters to avoid such cases. 

![](https://i.imgur.com/nFotRVe.png)

**Comment by napstr** [comment]
Setting the prefix requires admin perms. I don't see why we should be writing code and messages to handle restrictions for guild admins. They want to shoot themselves in the foot, I'm not the one taking time out of my day to stop them.

**Comment by knight-ryu12** [comment]
I'd say add restriction length to like 1~16

**Comment by OtterBoops** [comment]
It was moreso a security concern. In case we're sure that it cannot be abused for injection or setting an insanely long prefix to eat up space/crash (although extremely unlikely), this can be closed.

**Comment by napstr** [comment]
This could be relevant to have a check in place in the db API / possibly the row itself, when we talk about wanting the prefix decently presented in a dashboard (and thus limiting the length to something presentable), and preventing users from inserting giant prefixes into the table through calls to the backend from the dashboard.
