### ISSUE TITLE
PlayCommand incorrectly takes arguments


### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#478]
Seems there is problem at argument handling in PlayCommand.

https://i.imgur.com/NFDOh5k.png

**Comment by napstr** [comment]
Should be fixed / the effect lessened as of https://github.com/Frederikam/FredBoat/commit/6710f0de7fcf0ff6576963a7cc211c6342479575

**Comment by knight-ryu12** [comment]
Yeah thanks, isn't this in lice yet?
