### ISSUE TITLE
;;playnow command

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#48]
Proposal:
;;playnow <n>
This command skips the current track and moves the nth track into the player instead.

**Comment by napstr** [comment]
I recommend touching this after #210 and #245 are resolved, as they change the behaviour/refactor relevant classes for this.

**Comment by JustinHowe** [comment]
I would also love to see this in the features list. 

;;playnow n (n=index of desired song in playlist to play next)

Increments the song index of all songs less than the value of n, and decrements the index of all songs greater than the value of n. Changes n to 1 (or 0, depending on base index).

**Comment by babdab9** [comment]
This can ene acheived from the `;skip` command, is that correct?

**Comment by JustinHowe** [comment]
;;skip skips to the next song. Anything it skips is removed from the queue. ;;playnow would be a way to bring a song in the queue to the front.

**Comment by babdab9** [comment]
I think that was suggested somewhere :thonk:

**Comment by Frederikam** [comment]
Fixed by https://github.com/Frederikam/FredBoat/pull/553
