### ISSUE TITLE
;;skip should readd the skipped song to the end of the queue if the queue is set to be looped

### ISSUE THREAD

**Issue by LordPsycho202** [Frederikam/FredBoat#484]
Whenever a song is finished playing in a looped queue, it readds the song to the end of the queue. Skipped should have the same behavior, where it instead of removing the song entirely from the queue, it should readd it to the end of the queue.  A command like ;;remove would be needed to remove it from the queue altogether, but this seems like it is truer to the definitions of the commands.

**Comment by napstr** [comment]
>Skipped should have the same behavior

Why?

**Comment by Shredder121** [comment]
This has already been asked, by me even.
It used to be that skip kept the song, but it was unintended behavior.
The way currently to skip and keep the song is `;;fwd 1:00:00` or some other large time.

**Comment by napstr** [comment]
Previous discussion: https://github.com/Frederikam/FredBoat/issues/199#issuecomment-310708666

@LordPsycho202 Feel free to add more comments if there are questions remaining or you want to propose a change that does not change established conventions.
