### ISSUE TITLE
;;skipto command

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#49]
Proposal:
;;skipto <n>
This command skips all tracks until the nth track is reached in the queue.

**Comment by santhosh82** [comment]
Hi, I want to solve this. I am new to open source community.

**Comment by Frederikam** [comment]
Welcome!

Do you need an explanation of how FredBoat works and what it is, or are you already using it?

You can find the javadoc for JDA [here](http://home.dv8tion.net:8080/job/JDA/Promoted%20Build/javadoc/)

**Comment by santhosh82** [comment]
Hi Frederikam, I would be glad if you could provide some info. No, I didn't use FredBoat before.  I will be more glad if you could guide me a little?

**Comment by Frederikam** [comment]
In which case you'll want to check out the user documentation and try playing around with the music commands, particularly the ;;skip command

 http://docs.frederikam.com/

From there on you'll want to clone the `development` branch and add a new class of the type `Command`.

**Comment by santhosh82** [comment]
ok. I will do that and get back to you. Thanks for the help.

**Comment by napstr** [comment]
I recommend touching this after #210 and #245 are resolved, as they change the behaviour/refactor relevant classes for this.

**Comment by knight-ryu12** [comment]
Sure thing.

**Comment by napstr** [comment]
Whats the difference of this to `;;skip 1-n`?

**Comment by knight-ryu12** [comment]
Yeah... I think I'll just write alias code and invoke ;;skip 1-n

**Comment by Baschdel-98** [comment]
Hello there,
is this issue still active?
If unterstand the skip-command correctly, it is possible to enter the number of songs to skip as parameter.
Isn't that the same thing as skipto?

**Comment by Frederikam** [comment]
Yep, you're right.
