### ISSUE TITLE
Randomly stucking music playback on discord servers.

### ISSUE THREAD

**Issue by MBTheGamingMaster** [Frederikam/FredBoat#493]

**Comment by Frederikam** [comment]
If you mean that the bot is stuttering/lagging see this
![image](https://user-images.githubusercontent.com/2582617/39417592-9fe25808-4c55-11e8-817f-78326a33f386.png)
Nevertheless, this issue looks invalid.

**Comment by Shredder121** [comment]
*No description provided*.

Please provide a description, this doesn't help at all.
