### ISSUE TITLE
Java JDK 9 has reached end of life

### ISSUE THREAD

**Issue by AeonLucid** [Frederikam/FredBoat#494]
For reference http://www.oracle.com/technetwork/java/eol-135779.html.
Please ~revert to Java JDK 8 or~ update to Java JDK 10.

**Comment by shikhir-arora** [comment]
The backend is already updated to Java 10 and the rest will follow soon I'm sure, but there are no issues running the bot with Java 10.

**Comment by Macley-Kun** [comment]
Can confirm that DEV branch fredboat works perfect on 10.

I’m not sure of stable. But I assume it would.

**Comment by napstr** [comment]
FredBoat will not be reverted to Java 8. Please be invited to PR in Java 10 if it is important to you.

**Comment by Frederikam** [comment]
FredBoat is moving to Java 10 in the next major release https://github.com/Frederikam/FredBoat/commit/dd1681fedc1a7595c6e57927c0ff0fcba5636922
