### ISSUE TITLE
SUGGESTION: Lower default sound level

### ISSUE THREAD

**Issue by TheXydez** [Frederikam/FredBoat#498]
Using the publicly hosted FredBoat.

Make music play at a reasonable sound level, so you don't have to lower the bot to 2%?

**Comment by napstr** [comment]
How do you suggest to determine a "reasonable sound level"?

**Comment by Frederikam** [comment]
Not possible due to technical limitations. We would have to re-encode all audio, which kills performance.

**Comment by napstr** [comment]
Maybe not for the public bot, Fred, but it is generally a legitimate idea for the patron bot.

**Comment by Frederikam** [comment]
You mean #446?

I don't think that is what is being suggested here

**Comment by TheXydez** [comment]
@Frederikam 

Are you saying that YouTube audio is encoded with the volume cranked up to 110%?
I tested this by playing a video, first using FredBoat at 100% volume _(Which probably severely damaged my ears, heh)_, and then playing it on youtube with 100% volume. The volume is twice as high on Discord. You know why?

**Comment by Frederikam** [comment]
Check your output settings for Discord. The audio is unmodified.

**Comment by TheXydez** [comment]
Hmm.
![discord_2018-05-17_15-58-06](https://user-images.githubusercontent.com/30057780/40182187-22d2b5e4-59eb-11e8-8094-1d3753ad2481.png)
Seems legit to me?

**Comment by shikhir-arora** [comment]
> If I play FB at 2%, it's basically quiet. 

> Someone else plays it at 2% with their Discord volume at maximum and 4 subwoofers, then they may think it's loud.

> Depending on the situation, I may want the music louder, but another user may not. Maybe I'm not in a game and they are. 

There's Discord volume settings for this. My point is, as @napstr said originally, "default audio volume" -- or *suggested* audio volume is too subjective. If one wants they can use the $2+ Patron bot and have volume command, but even Discord volume works.


And by default, most YouTube videos have their audio frames sent straight to Discord, without any change.

**Comment by TheXydez** [comment]
> How do you suggest to determine a "reasonable sound level"?
I'm not saying we need something perfect, I'm just saying the current audio volume is **terrible**. I don't really know anyone who would need to raise the volume to above 20%.

**Comment by shikhir-arora** [comment]
I run it at 100% with 100% (so flat, default) - that sounds perfect. I adjust my volume using a physical controller for my audio interface, in my case, but check your computer settings. That doesn't sound right at all.

**Comment by Frederikam** [comment]
Even if it was viable to reduce the default volume, most people would instead have too low volume.
