### ISSUE TITLE
DB alternative

### ISSUE THREAD

**Issue by vpontin** [Frederikam/FredBoat#500]
Is possible to user another database engine (eg. mysql, sqlite, h2) instead of postgresql? I want to run it on my raspberry pi and dont want to install another big db engine due to space and processing power (i already have mariadb on it).

Thanks in advance!

**Comment by Frederikam** [comment]
We've already tried this with SQLi, but it was too difficult to maintain, so we ended up removing it.

**Comment by Kurozume** [comment]
You could try using ElephantSql for your Database, it's free and should be more than enough for your needs.
The problem with using other database engines is that FredBoat would need to be coded to use them, which can become complex rather quickly

**Comment by napstr** [comment]
Not without someone putting in the time and work to support it continuously. This is not a trivial task because FredBoat takes advantages of database specific features of postgres. This was a deliberate decision, and there are no plans to revert it.

**Comment by vpontin** [comment]
Ok. Anyway thanks for the response.
