### ISSUE TITLE
Feature Request: Mixcloud

### ISSUE THREAD

**Issue by xtechgamer735** [Frederikam/FredBoat#501]
Fred is amazing don't get me wrong, but he would be even more awesome if he could listen to mix cloud.

Do you think support is something that would be possible to add in?

Cheers!

**Comment by Frederikam** [comment]
FredBoat uses Lavaplayer to play music. You may want to submit an issue upstream about this.

https://github.com/sedmelluq/lavaplayer/issues

**Comment by xtechgamer735** [comment]
Awesome thanks! I’ll give them a prod :)
