### ISSUE TITLE
[Cutting Edge] Play command deletes the incorrect message

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#512]
Steps to reproduce:
1. Try to play a song using `<<play [Search term]`
2. Pick the desired track out of the displayed list using `<<play 1-5`

Expected result:
Bot deletes both the list of 5 songs and the user's pick

Actual result:
Bot only deletes the user's pick and leaves the list of tracks up, instead of `Song X has been selected`

**Comment by Frederikam** [comment]
The expected result is that the list of search results is edited, not deleted

**Comment by OtterBoops** [comment]
Sorry for that. You're right. What I meant is that the correct response is not displayed.

**Comment by Frederikam** [comment]
That commit was meant to mention #511

**Comment by Frederikam** [comment]
:ok_hand: 
![image](https://user-images.githubusercontent.com/2582617/42947335-6c45089a-8b6d-11e8-94ba-6ba2ca1db39a.png)
