### ISSUE TITLE
[Cutting Edge] Fun commands with mentions error out when such isn't provided

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#514]
After testing some of the fun commands, as reported by a user in the channel, I've found out that `<<pat` and `<<hug` return an error when a mention is not provided. The commands work fine **with** a mention.

Steps to reproduce:
1. Use `<<pat`  or `<<hug` without a mention.

Expected result:
The bot returns an image without user2user interaction ("Pats @[name]")

Actual result:
Error

**P.S.** It is also worth mentioning that when providing a mention, the bot only returns the image, as opposed to "Pats @[name]" or "Hugs @[name]" + the image.

**Comment by DaijobuDes** [comment]
Only Fredboat Cutting Edge has this issue. Other Fredboats work well.
