### ISSUE TITLE
[Cutting Edge] The bot gives an error message when trying to queue a Spotify playlist

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#516]
After a report in #cutting-edge-bugs we have discovered that FredBoat Cutting Edge will not play Spotify playlists, but rather give an error message.

![image](https://light-theme-hurts.my-ey.es/4b7c82.png)

Issue was replicated by Raven(as shown above), and by me.

Steps to reproduce:
1. Try to queue a Spotify playlist with the `;;play` command.

Expected result:
The bot queues the songs from the Spotify playlist and starts to play them.

Actual result:
Error shown above.

**Comment by Frederikam** [comment]
Not a bug, the bot has not been given spotify credentials. It should probably display a proper error for that.

**Comment by Frederikam** [comment]
Credentials have been added
