### ISSUE TITLE
make ;;uptime only show uptime and not additional stats with it!

### ISSUE THREAD

**Issue by thisisjvgrace** [Frederikam/FredBoat#520]
So, when we execute `;;uptime` command, FredBoat also sends the additional stats which kind of looks like spam. It's like, you execute `;;np` command but FredBoat would also posts the queue output along with now playing info. :D (Speaking from a selfhoster's perspective)

otherwise, FredBoat kun is very dank bot. 

![2018-07-29_16-26-03](https://user-images.githubusercontent.com/24418520/43365564-5e1a2cb4-934c-11e8-99ae-b703dcca9558.png)

With all due respect,
Jyu Viole Grace.

**Comment by smriga-jan** [comment]
Hello, 
I can see that command ";;uptime" is only an alias for ";;stats command". 
Can I create a separate command ";;uptime" to only show uptime?

**Comment by Frederikam** [comment]
@smriga-jan sorry for the late reply.

You're welcome to, although you'll want to work on the `sentinel` branch. Please read its contribution guide: https://github.com/Frederikam/FredBoat/blob/sentinel/CONTRIBUTING.md

**Comment by smriga-jan** [comment]
@Frederikam thank you for your reply!

I will read this guide carefully and look into it.
