### ISSUE TITLE
Is the bot broken ?

### ISSUE THREAD

**Issue by macaca50507** [Frederikam/FredBoat#524]
I am not really sure whether the bot is broken.
But today it just can't play any music even it is already add into queue.
And the ;;skip command is also broken , is said it had skip the current song but When I type ;;queue the song was still in queue.

With all due respect,
Macaca

**Comment by Shredder121** [comment]
> the bot

Can you be more specific?
Then we can look into it.

Also it's better to go to our Discord.

**Comment by macaca50507** [comment]
Hi , here's my channel and thanks for your reply.
https://discord.gg/NdD6t7
With all due respect,
Macaca

**Comment by macaca50507** [comment]
It's ok right now thx!
With all due respect,
Macaca

**Comment by Frederikam** [comment]
This issue tracker is not for general support questions. Please seek help at https://discord.gg/cgPFW4q
