### ISSUE TITLE
[Cutting Edge] Debug command displays text channel's permissions incorrectly.

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#533]
Steps to reproduce:
1. Set up two new text channels.
2. Add Regular/Patron boat.
3. Give them a role that has the same permissions for the two new text channels - First one should be Read only, the second one should be Read and Send messages.
4. Issue `<<debug` command.

Expected result:
Both bots display the same permissions.

Actual result:
Discrepancy between Regular Boat (which has everything correct) - https://owo.whats-th.is/0e6f4c.png
And CE - (Which thinks Read permissions means it can speak in the channel) - https://owo.whats-th.is/cbdf02.png

Bonus image:
It seems like it only affects text channels - https://owo.whats-th.is/873171.png

Bonus image 2:
Permissions for the role. `@everyone` has everything X-ed.
https://owo.whats-th.is/cc011f.png
https://owo.whats-th.is/ab032f.png

**Comment by Frederikam** [comment]
This should be fixed now
