### ISSUE TITLE
;;shards command should be DJ restricted

### ISSUE THREAD

**Issue by urielrocks5676** [Frederikam/FredBoat#539]
It was suggested that in order to avoid spam, it shouldn't be available to users, only problem is that it has been move up to where you have to be admin, we should move it down to DJ

**Comment by Nanabell** [comment]
I don't see a reason why DJ's need to be able to get a detailed list of the shard status tbh

**Comment by Frederikam** [comment]
Perhaps a rewrite is in order, as the current output wasn't intended for this many shards. Nevertheless, the command is too spammy for DJ permissions. Use it in a server where you have permission instead. It isn't context-aware anyways.
