### ISSUE TITLE
Error on startup "JSONObject["beta"] not a string"

### ISSUE THREAD

**Issue by daveb778** [Frederikam/FredBoat#55]
Hi no matter what i do to the config files i get a error when trying to self host fredboat. I attached some screenshots down below and i double check that i have the latest version of java and yes i blurred out the client key in the screenshot.

https://puu.sh/tnGKj/38a2015202.png
https://puu.sh/tnKg4/186acc1cec.png

**Comment by daveb778** [comment]
So i have a bit of a update i tried removing the "beta" line from the config but that resulted in it saying beta line if missing. Now i tried replacing null with a . and that resulted in the tokens failing.
https://puu.sh/tnKHA/654c8e1e67.png

**Comment by Frederikam** [comment]
The problem is that the bot thinks it is in development mode. That must have been my fault since I left the default configuration like that. Here's what your config.json file should probably look like:
```json
{
	"patron": true,
	"development": false
}
```

**Comment by daveb778** [comment]
Thanks for the reply, that seemed to help but now its showing about about the credentials file. Also i havent changed the file since.
https://puu.sh/tnZUR/e426ea8cf0.png
https://puu.sh/tnZS1/ae26ef3207.png

**Comment by Frederikam** [comment]
Invalid JSON syntax on line 3. You must specify a value for each key but you left it blank.

**Comment by daveb778** [comment]
I had keys in all of them but i deleted them for the screenshot.

**Comment by Frederikam** [comment]
Please make sure you also have your client token surrounded by quotation marks and ending with a comma. Your JSON is not valid.

**Comment by daveb778** [comment]
I added quotes and a comma still no luck.

**Comment by daveb778** [comment]
Would you mind if i emailed you the config file?

**Comment by Frederikam** [comment]
Not really, but you could just use a JSON parser like
http://jsonviewer.stack.hu/ to check for yourself.

**Comment by daveb778** [comment]
I pasted it in the viewer then clicked format copied that to the text json file and still puts out the same error.
Also i sent the files i have to the gmail on your profile, thanks for all the help.

**Comment by flaxues** [comment]
I'm having the same problem
