### ISSUE TITLE
Add a default radio when there's no queue

### ISSUE THREAD

**Issue by urielrocks5676** [Frederikam/FredBoat#571]
#277 and #418, both have a idle music, I recommend using radio or live streams instead, adding a way to configure this and updating the join message to point the feature out would be useful. Make this a patron only feature.

**Comment by Frederikam** [comment]
This is essentially a duplicate of #277 and #418. From a technical perspective, finite tracks and live streams are handled mostly the same. See Shredder's comment in #277.
