### ISSUE TITLE
No sound from Fredboat

### ISSUE THREAD

**Issue by JohnAngel9** [Frederikam/FredBoat#575]
Fredboat responds as normal to commands, is not muted, yet there is no music playing for anyone on the server. Discord shows that it's "talking" but no sound can be heard whatsoever, friends can't hear either. We made a new server and it plays normally.

**Comment by OtterBoops** [comment]
Hop on over to https://discord.gg/cgPFW4q and go through the appropriate channel to receive technical support with Fredboat. The github issues page is mostly used for bugs that are confirmed by staff members in the Support Server.
