### ISSUE TITLE
Automatic Voice Channel Extension

### ISSUE THREAD

**Issue by LudusLight** [Frederikam/FredBoat#578]
This is a concept that I've not seen very often in Discord bots, and as a music bot, FredBoat seems like a great recipient for this feature. I want to get opinions on this before possibly making a PR.

The idea is to automatically extend (clone) a voice channel when someone joins it, so that there is always another voice channel for someone to join, and then remove it after it is empty. This is a great solution that eliminates voice channel clutter in large Discord servers.

Additional ideas to enhance the feature:

- Option to decide the maximum number of extended voice channels at any one point
- Option to give limited permissions to the first person who joins a cloned voice channel, such as the ability to change the name or maximum number of users allowed (perhaps other commands for the 'owner' of the channel as well?)
- Ability to exclude or include voice channels that would be extended (such as excluding an AFK channel, or including a general channel)

**Comment by Nanabell** [comment]
I'm not quite sure if this feature would benefit Fredboat that much, this feature seems to be more targeted towards moderation/utility/ICanDoEverythingPleaseInviteMeToAllYourServers Bots.

If bots were able to join multiple voice-channels in the same server I think your feature suggestions would have made a lot of sense but that is sadly not the case.
Is there another reason why we need this feature other than just extending the features of Fredboat?

**Comment by LudusLight** [comment]
Although it isn't strictly music based, the fact that it is related to voice channels makes me feel like this feature would be well enough related to FredBoat's scope that it would be well received. I admit that it is indeed an extension of features, but it is one that is at the least somewhat related to FredBoat's function.

As for being a moderation utility, I agree, however do note that FredBoat already includes moderation utilities (though primitive).

**Comment by Frederikam** [comment]
I think this feature is too niche to be very useful, and it is going to be rather complicated to implement with the code that we currently have.
