### ISSUE TITLE
Run without docker

### ISSUE THREAD

**Issue by vico93** [Frederikam/FredBoat#590]
Since Youtube disabled stream in the official instance of FB i reprofiled my old raspberry pi to run an instance myself, but i want to run it without docker (to keep my pi with less possible dependencies).

Is possible?

**Comment by Frederikam** [comment]
> Since Youtube disabled stream in the official instance of FB

Selfhosting won't fix that. This is not limited to FredBoat either.

> ...raspberry pi to run an instance myself...

I wouldn't recommend that. This kind of music playback is not well-optimized for ARM. You *might* be able to get one stream playing smoothly.

> ...run it without docker...

This is terribly difficult with FredBoat, and I won't be there to help you without Docker.

> to keep my pi with less possible dependencies

You've missed the point of containerization. Containers are self-contained. Without Docker you would have to install the dependencies on your actual host system.

> Is possible?

With much effort.

---

If you really must run a music bot on a raspberry pi, there are music bots more suited than FredBoat.

**Comment by vico93** [comment]
Ok thanks
