### ISSUE TITLE
Persistent server settings

### ISSUE THREAD

**Issue by urielrocks5676** [Frederikam/FredBoat#593]
This will require some tinkering, but due to the fact that we have to reboot Everytime we get blocked by YouTube, the settings are not stored for each server, causing some annoyed users to have to reset permissions and prefixes. Unfortunately it means also more data to be stored.

**Comment by napstr** [comment]
Which settings do you mean?

**Comment by Frederikam** [comment]
This is an operations issue with the patron bot. Not a development issue. Server settings are inherently persistent. Closing.
