### ISSUE TITLE
fred boat skiping songs

### ISSUE THREAD

**Issue by Mewth16** [Frederikam/FredBoat#60]
okay so i tried to load a playlist with 2,947 videos and it only loaded 600 little disappointed there. but ive noticed that when the bot starts to lag and it stops (audio stop Playing) for a few seconds it will go to the next song

**Comment by Frederikam** [comment]
I noticed. I am investigating right now

**Comment by Frederikam** [comment]
This has been resolved. The problem was a recently added node from a friend with unstable internet.
