### ISSUE TITLE
Prioritized tracks remain prioritized with the 'all' repeat mode

### ISSUE THREAD

**Issue by badg0n** [Frederikam/FredBoat#612]
If I use ;;playtop while there already is a queue, the command works fine. Then, after the playtop track has been played, the next song from the queue is playing. But then, after the next song, the playtop song is playing again. And then again a song from the queue and then the playtop song again repeatedly.

Scheme:
playtop song
1st queue song
playtop song
2nd queue song
playtop song
…

**Comment by badg0n** [comment]
When I use ;;playtop for two songs, only these two songs will alternate.

Scheme:
playtop song 1
playtop song 2
playtop song 1
playtop song 2
playtop song 1
…

**Comment by Frederikam** [comment]
Do you happen to have repeat mode enabled?

**Comment by badg0n** [comment]
yes

**Comment by Frederikam** [comment]
> yes, repeat all

That's your problem. Switch to none.

In repeat all mode, the tracks get added back to the queue. They should probably be added back without their priority status. I'll keep this issue open because of that.

**Comment by badg0n** [comment]
Right, it should be added to the end of the queue if playtop song has ended.

So you say one can either use playtop or repeat all. Since this is unintended, isn't it, can you please change it?

**Comment by Frederikam** [comment]
It may take some time for 0917c04 to actually reach production. There appears to be a bug affecting FredBoat at scale that I need to track down first.
