### ISSUE TITLE
Edit the message sent when ;;help is executed

### ISSUE THREAD

**Issue by LegalSmeagol** [Frederikam/FredBoat#618]
Hello.

I wonder, is there any way to edit the message that is sent when someone types ;;help?

FYI - I am self hosting

Thanks

**Comment by Frederikam** [comment]
You would have to edit the code in `HelpCommand`

**Comment by LegalSmeagol** [comment]
Where about would that be? I don't believe the jar is stored locally - not according to the guide in setting it up?

**Comment by Frederikam** [comment]
You need basic knowledge of Java, and in your case also Docker. This issue tracker is not the place to discuss specific changes. Maybe someone in the selfhosters channel can help. I'm currently very busy with an exam currently.
