### ISSUE TITLE
Feature: Add build instructions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by B-Knight49** [Frederikam/FredBoat#619]
A simple improvement that'll help new comers to the project and those somewhat unfamiliar with Docker and Kotlin. 

(I don't know how to properly build FredBoat after changes in my IDE).

**Comment by Frederikam** [comment]
How's this?

**Comment by B-Knight49** [comment]
That looks good, massively appreciated.

One thing I would suggest is maybe mentioning what to do with the Docker image once it has been built. I'm 90% sure we'd need to replace the `image:` in docker-compose.yml but the exact syntax of it I'm not aware.

...A small one too - maybe a mention of the Dockerfile's location. `<git>/FredBoat/dockerfile` for extra clarity. 

Thanks again.

**Comment by Frederikam** [comment]
You're welcome. Was there anything else?

You're also welcome to submit a PR if you have any exact words to add.

**Comment by B-Knight49** [comment]
Perfect. That's helped a bunch. 

If I think of anything else, I'll submit a PR. Cheers.
