### ISSUE TITLE
SELFHOSTED - stop command makes the bot leave the channel 

### ISSUE THREAD

**Issue by koopernick** [Frederikam/FredBoat#628]
Hello,

I hope this is the correct place for issues related to the selfhosted version of the bot.

I have installed the selfhosted yesterday via docker and it works like a charm (thank you for that !).

However, the "stop" command makes the bot leave the channel. According to the FAQ, the stop commands should only stop the current song and clear the queue. 

So right now, everytime I stop the music, I must use the "join" command to re-invite the bot in the current channel (which triggers the discord notification and it's kind of annoying).

Let me know if I'm missing something or if you need more informations.

Thank you.

**Comment by OtterBoops** [comment]
That is the intended behavior of the bot. If you want it to stay in the channel, use skip. Also the correct place for selfhosting questions is our discord server. https://discord.gg/cgPFW4q

**Comment by koopernick** [comment]
Thanks for the quick answer.

I tried your discord but I didn't have the rights to post in the self hosted section.

Skip only skip the current song. Is there a command to purge the queue without the bot leaving the channel ?

**Comment by OtterBoops** [comment]
![Discord_XxdwQxbJqR](https://user-images.githubusercontent.com/4331679/85870774-30554380-b7d6-11ea-88b2-36f41011876f.png)
