### ISSUE TITLE
[Feature Request] Play direct links to mp3, wav, or other music files

### ISSUE THREAD

**Issue by KyuseishuSavior** [Frederikam/FredBoat#632]
I have recently decided to switch from another music bot to FredBoat, and I was a bit miffed when I found out direct links couldn't;t be played. My friend likes to make music but not really upload anywhere else other than discord, so I used to copy the link from the music file and add it as a song, but when I checked 5 days ago, he couldn't do it.

**Comment by OtterBoops** [comment]
Feature is available on a selfhosted instance, turned off on the public bot due to the risk of getting ddossed.

**Comment by Frederikam** [comment]
This is not something we want to make available on the public version
