### ISSUE TITLE
;;play command not adding songs to queue but confirming selection

### ISSUE THREAD

**Issue by CladesAffero** [Frederikam/FredBoat#68]
tried adding songs by link and youtube search functions, songs i try to add but if another user adds a different song it works perfectly. Issue repeats on other users if trying with songs i tried to add first. 

i have 2 groups with bot active issue repeats on both sides

;;play https://www.youtube.com/watch?v=5ZHl7qVZqpo
;;play imagine dragons radioactive
;;play https://youtu.be/dGlLX-DsdEg

**Comment by Frederikam** [comment]
Already trying to patch this

**Comment by CladesAffero** [comment]
thanks i <3 you

**Comment by Frederikam** [comment]
Forgot to close this 
![image](https://cloud.githubusercontent.com/assets/2582617/22461744/c5290410-e7aa-11e6-8b70-ab5561b12124.png)

**Comment by Disputes** [comment]
yeah it was pretty weird, mine managed to play a song but it was weird pulsating static (hard to describe it tbh). was quite a wtf moment. friend was complaining saying fredboat was better yet the private bot IS fredboat but the with the command prefix changed to ! as im not a fan of ;;
