### ISSUE TITLE
Suggestion: Prefix editing

### ISSUE THREAD

**Issue by Disputes** [Frederikam/FredBoat#69]
would it be possible to allow users to edit the prefix without having to dig into the java files and editing the return messages and the prefix constant?

so for example: if you dont want ;; as your prefix you can set in the config.json to be !

thanks

Also Manage messages, permission is enabled for the bots role but it wont do ;;clear. if you want i can create a second

**Comment by Frederikam** [comment]
This is currently planned to be a feature to go alongside https://github.com/Frederikam/FredBoat/issues/23

And yes, I know the clear command is broken.

**Comment by TheWolfy** [comment]
You can create a Youtuber grade

**Comment by napstr** [comment]
Trying to break this down into steps:

- [ ] Make FredBoat universally react to mentions, like so: `@FredBoat play <link>`.
This requires adjusting the regex for parsing the CommandContext. This is important so that there is always a fallback if a weird prefix is set / to find out the current prefix.
- [ ] create a prefix command, that saves the prefix in the GuildConfig entity.

**Comment by napstr** [comment]
One edge case to keep in mind when testing this would be empty prefixes.

**Comment by Nanabell** [comment]
if empty fallback to `;;`

**Comment by napstr** [comment]
I am thinking of empty prefixes as a feature here. It needs the following questions answered when implementing: How to set it? How to persist it and differentiate from the default prefix? How to regex it?

**Comment by Nanabell** [comment]
as general question **SHOULD** we continue to use regex? or should we limit ourself to a simple string? if we stay with the regex do we allow or even force users to use regex as well or limit them to simple strings?

**Comment by napstr** [comment]
Good question probably just going to use String#startsWith.

**Comment by napstr** [comment]
This issue is solved: Selfhosters can edit the default prefix of their whole bot in the config file (this was possible for some time), guild admins can edit the prefix in their guilds since #375 .
