### ISSUE TITLE
Intermediate: Volume controls

### ISSUE THREAD

**Issue by linky00** [Frederikam/FredBoat#71]
Some music really is too loud. Please may someone add proper volume controls to the bot? Thanks!

**Comment by Nanabell** [comment]
Fredboats Volume control used to exist but was disabled on the MainBot due to the heavy load it put on the Bot which decreased its performance globally

**Comment by Frederikam** [comment]
![image](https://cloud.githubusercontent.com/assets/2582617/22661732/c3747d92-eca6-11e6-9450-358b98d59151.png)

**Comment by linky00** [comment]
Sorry! Thanks.
