### ISSUE TITLE
Bot gives error when trying to dm a dump

### ISSUE THREAD

**Issue by LoyalNine1487** [Frederikam/FredBoat#72]
When you do a ;;dump -q or ;;dump 200 -r the bot respawns with
`java.lang.NumberFormatException: For input string: "-q"
    java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    java.lang.Integer.parseInt(Integer.java:580)
    java.lang.Integer.valueOf(Integer.java:766)
    fredboat.command.util.DumpCommand.onInvoke(DumpCommand.java:53)
    fredboat.commandmeta.CommandManager.prefixCalled(CommandManager.java:105)`

**Comment by Frederikam** [comment]
It seems you are using the command wrong. Proper usage:
```
;;dump 150
;;dump -q 150
```
You can't do this:
```
;;dump 150 -r
;;dump -q```

Last argument expected should be a number. `-r` has never been an option.
