### ISSUE TITLE
Music can not be bent.

### ISSUE THREAD

**Issue by suiginn** [Frederikam/FredBoat#73]
I'm a beginner program.
"Http://docs.frederikam.com/selfhosting" I did it as written on the site, but music did not flow
How do I get music to flow?

**Comment by suiginn** [comment]
Currently we have confirmed the following errors.

Exception in thread "JDA AudioConnection Guild: 268663931692777486 Ready Thread" java.lang.UnsatisfiedLinkError: Required library at /natives/darwin/libudpqueue.dylib was not found
At com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary (NativeLibLoader.java: 93)
At com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load (NativeLibLoader.java: 77)
At com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManagerLibrary.getInstance (UdpQueueManagerLibrary.java: 13)
At com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager. <Init> (UdpQueueManager.java: 26)
At com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager (NativeAudioSendFactory.java: 31)
At com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance (NativeAudioSendFactory.java: 58)
At com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start (NativeAudioSendSystem.java: 22)
At net.dv8tion.jda.core.audio.AudioConnection.setupSendSystem (AudioConnection.java: 225)
At net.dv8tion.jda.core.audio.AudioConnection.access $ 200 (AudioConnection.java: 47)
At net.dv8tion.jda.core.audio.AudioConnection $ 1.run (AudioConnection.java: 123)

**Comment by Frederikam** [comment]
It looks like you are trying to host FredBoat on a Mac. FredBoat depends on https://github.com/sedmelluq/lavaplayer to play music, which does not seem to support Darwin (the OSX kernel).

This normally wouldn't be a problem for a Java library, but this library isn't pure Java.

**Comment by sedmelluq** [comment]
LavaPlayer itself works on OS X, but the native audio packet send system doesn't. Remove `.setAudioSendFactory(new NativeAudioSendFactory())` part in `FredBoatBot` class if you want to run it on OS X.

**Comment by Frederikam** [comment]
Thanks for clarifying Sed. I thought lavaplayer itself didn't support `darwin`.

When running on `arm` architecture we have a special case to disable NAS, I should simply patch this to also check for `darwin`.

I will do this later as I am very busy right now.

**Comment by knight-ryu12** [comment]
`if(!System.getProperty("os.arch").equalsIgnoreCase("darwin")) {
 builder.setAudioSendFactory(new NativeAudioSendFactory());
}`
will work, insert into development branch, at FredBoatBot.java L66 
Let me know if it worked.

**Comment by Frederikam** [comment]
This issue should now be fixed. Compile from the `development` branch to get the fix.

**Comment by kitkatdesu** [comment]
`Master` branch not working on macOS 10.12.2 Sierra, the `System.getProperty` check must not be finding macOS. Commenting out that entire line (including `setAudioSendFactory`) and then re-building works (now playing music 🎶 ).
