### ISSUE TITLE
[Future Project] adding comment on config/creds.json

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#76]

**Comment by Frederikam** [comment]
You can't really add comments to a json file. You can add notes in the form of string values, but that's an ugly hack.

Alternatively you can parse the json files while ignoring comments, but this is something org.json is incapable of.

**Comment by knight-ryu12** [comment]
Yeah, that's what I think of,
Kinda need better document about config/creds.json

**Comment by napstr** [comment]
Why not use a different file format for the config, one which allows comments?

**Comment by Frederikam** [comment]
I have actually been thinking of using something else like javascript, but I have much bigger priorities atm.
