### ISSUE TITLE
Youtube live video

### ISSUE THREAD

**Issue by ajdin1997** [Frederikam/FredBoat#79]
I dont know where to post new ideas, it would be nice if we can play live videos also. Great bot.

**Comment by Frederikam** [comment]
FredBoat relies on lavaplayer to play audio from youtube, so it would be a https://github.com/sedmelluq/lavaplayer issue

**Comment by napstr** [comment]
This seems to work. I tried a few live streams from here:
https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig
and they worked fine.

This might have been introduced with todays update, maybe earlier.
@ajdin1997 can you confirm what you wanted is working?
@Frederikam this can probably be closed

**Comment by Frederikam** [comment]
Yes, this was introduced in the latest update, alongside beam.pro support.
