### ISSUE TITLE
Help! FredBoat Offline?

### ISSUE THREAD

**Issue by vonalyn** [Frederikam/FredBoat#80]
FredBoat went offline, and I have no idea how to turn it back on. It ignores any command (presumably because it is offline), is there a command I'm missing to turn it back on?

**Comment by Rayunara** [comment]
I'm having the same issue, could we please get some light shined upon this ?

**Comment by knight-ryu12** [comment]
Because of Bot token revoke, need to get bot owner
sadly there is no ETA for that.
Sorry!

**Comment by knight-ryu12** [comment]
*might close this plz*

**Comment by Frederikam** [comment]
This has now been fixed. I plan to post an announcement later once I've actually left my bed.

**Comment by Punkcln** [comment]
The bot becomes online from time to time. Still doesn't respond to any command. I tried kicking the bot and inviting to the server again, but the problem still persists.

**Comment by Frederikam** [comment]
Experiencing network issues now
