### ISSUE TITLE
Todo for Chromaryu

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#82]
- [x] make ;;userinfo more better: ID search if User search fails.
- [x] make ;;userinfo more privacy: check user server.

**Comment by Frederikam** [comment]
The bot should already do the first thing with https://github.com/Frederikam/FredBoat/blob/master/FredBoat/src/main/java/fredboat/command/util/UserInfoCommand.java#L58

Not sure what you mean with the second thing.
