### ISSUE TITLE
make ;;queue (or some other command) show by whom a song was requested

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#83]
In the ;;queue command, show for each song by which user it was requested.

This has various benefits from catching trolls to people distributing song requests in a fairer way because they can see who has queued up many/none.

**Comment by Frederikam** [comment]
This would be rather easy to do given that the bot remembers who requested a song

**Comment by Nanabell** [comment]
wouldnt you need to store that in your db ? since the bot can reload playlists after restarts but if you store who queued what just when the bot is running you would loose that information on restart

**Comment by Frederikam** [comment]
@Nanabell The persistence system already handles this when it reads and saves the temporary files to the filesystem.

**Comment by Nanabell** [comment]
SeemsGoood!

**Comment by napstr** [comment]
Ye this was really easy to add. Now I'm just looking on how to properly include the " added by " text that I used to the internationalization system.

**Comment by Frederikam** [comment]
@napstr take a look at the `en_US.properties` file in the resource directory. You can change an existing translation as well, in which case I will just invalidate the current translations for that string on Crowdin.

Remember to also send a PR to https://github.com/Frederikam/FredBoat-i13n .

**Comment by napstr** [comment]
Ok, now the I18n test is failing because it is checking the id_ID language file against the default (en_US) one, and I added a line to en_US.
What is expected of my commit? Add the new entry to _all_ files using the en_US text? Or just add it to en_US and id_ID, assuming Crowdin will propagate it to all the other files?

**Comment by Frederikam** [comment]
The test is failing because the en_US file has translations that are missing in the other files. This problem would be solved when I upload the new source to Crowdin and commit the latest translation build.

**Comment by napstr** [comment]
Ok so I'll just add the line to en_US. I just hate breaking tests lol.

Does this look acceptable?

![image](https://cloud.githubusercontent.com/assets/6048348/23590793/c75aaa4e-01e6-11e7-8b5a-1a8ad06c8c2a.png)

**Comment by Frederikam** [comment]
The problem with this is that it is difficult to tell the title from `added by {1}`. Try figuring out a way of telling these elements apart. Maybe with some emphasis.
