### ISSUE TITLE
"Suspicious error when loading info"

### ISSUE THREAD

**Issue by WantaSpud** [Frederikam/FredBoat#91]
Every time we try to play a song or video from any link, we get the error "Suspicious error when loading info for 'URL HERE'" Need Help :(

**Comment by Frederikam** [comment]
Is this the public music bot or one you are hosting yourself?

If it's the former it has likely just been fixed. If it's the latter I need more info.

**Comment by WantaSpud** [comment]
It's been fixed. Thank you!
